-- Seed 100+ challenges across all 5 categories

insert into public.challenges (title, description, category, difficulty, requires_photo, requires_video, requires_text) values

-- PHYSICAL (25 challenges)
('Do 20 pushups right now', 'Drop and do 20 pushups. No breaks. Post your proof when you''re done.', 'physical', 1, true, false, false),
('Hold a plank for 60 seconds', 'Get into plank position and hold it for a full minute. Video yourself doing it.', 'physical', 2, false, true, false),
('Sprint for 30 seconds outside', 'Go outside and sprint as fast as you can for 30 seconds. Show us the aftermath.', 'physical', 2, true, false, false),
('Do 50 jumping jacks', 'Right now. 50 jumping jacks. We''re waiting. Post proof when done.', 'physical', 1, true, false, false),
('10 pull-ups or 20 negatives', 'Find a bar or door frame and do 10 pull-ups. No bar? Do 20 slow negatives. Post proof.', 'physical', 3, true, false, false),
('100 jump rope reps', 'Grab a jump rope or just pretend and do 100 reps. Photo when done.', 'physical', 2, true, false, false),
('Walk 1000 steps right now', 'Put your phone in your pocket and walk 1000 steps. Post your step count screenshot.', 'physical', 1, true, false, false),
('Do 30 squats', 'Full depth squats, 30 reps. No cheating. Post your proof.', 'physical', 1, true, false, false),
('Hold a wall sit for 90 seconds', 'Back against the wall, thighs parallel. 90 seconds. Video or photo evidence required.', 'physical', 2, false, true, false),
('Do 15 burpees', 'Full burpees. Touch the ground, jump up, clap overhead. 15 reps. Post proof.', 'physical', 3, true, false, false),
('Touch your toes 10 times', 'Slowly, full range. 10 reps. Post your flexibility proof.', 'physical', 1, true, false, false),
('Do 25 dips on a chair', 'Use a sturdy chair or bench. 25 tricep dips. Post your proof.', 'physical', 2, true, false, false),
('Run around the block once', 'Right now. Around the block. Post a sweaty selfie when you''re back.', 'physical', 2, true, false, false),
('Do a 5-minute yoga flow', 'Downward dog, child''s pose, warrior — 5 minutes. Photo when done.', 'physical', 1, true, false, false),
('Drink a full glass of water', 'Right now, 8oz minimum. Post proof. Hydration is a physical challenge too.', 'physical', 1, true, false, false),
('Do 20 mountain climbers', 'Fast, alternating legs, full range. 20 total reps. Post proof.', 'physical', 2, true, false, false),
('Balance on one leg for 60 seconds', 'Eyes open for 45s, eyes closed for 15s. Post your balancing act.', 'physical', 1, true, false, false),
('Do 10 slow push-ups with 3s pause at bottom', 'Three second pause at the bottom. Ten reps. This is harder than it sounds. Post proof.', 'physical', 2, true, false, false),
('Stretch for 5 minutes straight', 'Full body stretch. Hold each pose for 20+ seconds. Photo when done.', 'physical', 1, true, false, false),
('Do 20 calf raises on each leg', 'Single leg calf raises, 20 per side. Find a step if you can. Post proof.', 'physical', 1, true, false, false),
('Do 3 sets of 5 slow push-ups', 'Slow negatives, explosive up. 3 sets. Post the last set.', 'physical', 2, true, false, false),
('Skip or hop for 60 seconds', 'Skip, hop, or skip rope. 60 seconds non-stop. Post sweaty proof.', 'physical', 2, true, false, false),
('Do a handstand against the wall', 'Find a wall and kick up. Hold for at least 5 seconds. Video it.', 'physical', 3, false, true, false),
('Box breathe for 3 minutes', '4s in, 4s hold, 4s out, 4s hold. Three rounds. Post how you feel after.', 'physical', 1, false, false, true),
('Do 40 high knees', 'Run in place with high knees. 40 alternating reps. Post proof.', 'physical', 1, true, false, false),

-- CREATIVE (25 challenges)
('Write a haiku about what''s directly in front of you', 'Look at the thing nearest you. Write a haiku. 5-7-5 syllables. Post it.', 'creative', 1, false, false, true),
('Draw something from memory in under 2 minutes', 'Pick something you know well. Draw it from memory. No looking it up. Photo it.', 'creative', 2, true, false, false),
('Rearrange 5 objects near you into art', 'Grab 5 things nearby and arrange them into something. Photo the result.', 'creative', 1, true, false, false),
('Make a face using food or objects', 'Use food, objects, or whatever''s nearby. Make a recognizable face. Photo it.', 'creative', 1, true, false, false),
('Write a limerick about your day so far', 'AABBA rhyme scheme. Make it funny. Post it.', 'creative', 2, false, false, true),
('Take an interesting photo of something boring', 'Find the most mundane thing near you and make it look incredible. Post it.', 'creative', 2, true, false, false),
('Fold an origami shape from whatever paper is near you', 'Find paper, fold something recognizable. Photo the result.', 'creative', 2, true, false, false),
('Write a two-sentence horror story', 'The best horror is short. Two sentences. Make it disturbing. Post it.', 'creative', 1, false, false, true),
('Build the tallest tower you can from nearby objects', 'Use whatever''s around you. Stack it as high as possible. Photo it.', 'creative', 1, true, false, false),
('Describe your current location in the style of a travel guide', 'Wherever you are — make it sound incredible. Post your description.', 'creative', 2, false, false, true),
('Draw your pet or a nearby animal from imagination', 'No reference. Draw it. Photo the drawing.', 'creative', 1, true, false, false),
('Write a 6-word story', 'Legend says Hemingway wrote: "For sale: baby shoes, never worn." Beat that in 6 words.', 'creative', 2, false, false, true),
('Make shadow art with your hands', 'Find a light source and make the best shadow puppet you can. Photo it.', 'creative', 1, true, false, false),
('Find 3 things that are the same color and photograph them together', 'Look around. Find 3 objects with matching colors. Compose a photo.', 'creative', 1, true, false, false),
('Write a fake 5-star review for the room you''re in', 'Rate your current location like it''s a hotel on TripAdvisor. Post it.', 'creative', 1, false, false, true),
('Doodle your current emotion as an abstract shape', 'No words, no recognizable images. Just shapes and lines that represent how you feel. Photo it.', 'creative', 2, true, false, false),
('Name 5 songs that match your current mood and explain why', 'Think carefully. Make a mini-playlist and defend each choice. Post it.', 'creative', 1, false, false, true),
('Create a flat lay photo of everything in your pockets or bag', 'Empty it out. Arrange everything aesthetically. Photo it.', 'creative', 1, true, false, false),
('Write a one-paragraph short story that starts with "No one expected..."', 'Make it interesting. At least 100 words. Post it.', 'creative', 2, false, false, true),
('Make an instrument from nearby objects and play it on video', 'Tap, blow, rattle, whatever — make music with what''s around you. Video it.', 'creative', 2, false, true, false),
('Find the most aesthetically interesting corner of your space and photo it', 'Not the whole room — just a corner or small detail. Photo it.', 'creative', 1, true, false, false),
('Write a fortune cookie message better than any fortune cookie', 'Cryptic but meaningful. 1-2 sentences. Post it.', 'creative', 1, false, false, true),
('Draw a map of your current location from memory', 'Your house, office, neighborhood — draw it without looking it up. Photo it.', 'creative', 2, true, false, false),
('Take a photo that captures a specific emotion without showing a face', 'No faces. Just composition, light, objects. Make the viewer feel something.', 'creative', 3, true, false, false),
('Write tomorrow''s horoscope for yourself', 'Be specific, be weird, be ominous. Post it.', 'creative', 1, false, false, true),

-- SOCIAL (20 challenges)
('Compliment a stranger', 'Find someone near you and give them a sincere compliment. Ask if you can take a photo together.', 'social', 2, true, false, false),
('Text someone you haven''t talked to in 6+ months', 'Send a real message, not just a reaction. Post a screenshot (hide the name if you want).', 'social', 2, false, false, true),
('Leave a positive review for a local business right now', 'Google, Yelp, wherever. Make it genuine and specific. Post a screenshot.', 'social', 1, true, false, false),
('Tell someone near you something you appreciate about them', 'In person. Face to face. Don''t make it weird. Post proof they heard you.', 'social', 3, true, false, false),
('Send a voice message to a friend instead of texting', 'Pick someone and send a real voice message. Post that you did it.', 'social', 1, false, false, true),
('Ask someone near you about their day and actually listen', 'Have a real 5-minute conversation. Post what you learned about them.', 'social', 2, false, false, true),
('Call someone you''ve been meaning to call', 'No texts — actually call. Post that you did it and how it felt.', 'social', 2, false, false, true),
('Buy or make something for someone else', 'Coffee, snack, a note — something tangible. Give it to someone. Photo it.', 'social', 2, true, false, false),
('Post a genuine thank you message publicly', 'Twitter, Instagram, wherever — publicly thank someone specific and why. Post a screenshot.', 'social', 1, true, false, false),
('Start a conversation with someone you rarely talk to', 'Not a close friend. An acquaintance, coworker, neighbor. Post what you talked about.', 'social', 3, false, false, true),
('Share a skill or piece of knowledge with someone today', 'Teach someone something you know. Post what it was and who you taught.', 'social', 1, false, false, true),
('Introduce two friends who don''t know each other', 'Create a group chat or make an IRL introduction. Post that you did it.', 'social', 2, false, false, true),
('Write and send a handwritten note to someone', 'Find paper. Write something real. Give it to someone or mail it. Photo the note.', 'social', 2, true, false, false),
('Ask someone what they''ve been excited about lately', 'Not "how are you" — specifically ask what''s excited them recently. Post their answer.', 'social', 1, false, false, true),
('Give a stranger directions or help them with something', 'Find someone who looks lost or could use help. Help them. Post what happened.', 'social', 2, false, false, true),
('Tag a friend in something that made you think of them', 'A post, a meme, an article. Tag them publicly. Post a screenshot.', 'social', 1, true, false, false),
('Hold the door open for 5 people', 'Count them. Post how many people actually said thank you.', 'social', 1, false, false, true),
('Ask someone what their favorite book or movie is and why', 'Then actually write down their recommendation. Post what they said.', 'social', 1, false, false, true),
('Do something kind anonymously', 'Leave a note, pay for someone''s coffee, whatever — anonymously. Post what you did without revealing who benefited.', 'social', 2, false, false, true),
('Smile and say hello to 5 strangers', 'Actually do it. Count them. Post how many smiled back.', 'social', 1, false, false, true),

-- MENTAL (20 challenges)
('Write down 3 things you''re grateful for right now', 'Be specific. Not just "family" — what specifically about family? Post them.', 'mental', 1, false, false, true),
('Meditate for 2 minutes', 'Set a timer. No phone, no distractions. Just breathe. Post how you feel after.', 'mental', 1, false, false, true),
('Name 10 countries in under 30 seconds', 'Set a 30-second timer and write as many countries as you can. Post your list and count.', 'mental', 2, false, false, true),
('Write down 5 things that are going well in your life right now', 'Not wishes or hopes — things actually going well right now. Post them.', 'mental', 1, false, false, true),
('Memorize a 10-digit number in 2 minutes', 'Pick any 10-digit number. Memorize it. Write it without looking. Post your result.', 'mental', 2, false, false, true),
('Do 5 minutes of focused deep work with no distractions', 'Turn off everything. Work on one thing. Post what you accomplished.', 'mental', 2, false, false, true),
('Write down your #1 goal for this week', 'Not a list — one goal. Make it specific and achievable. Post it.', 'mental', 1, false, false, true),
('Count backwards from 300 by 7s', '300, 293, 286... Go until you reach under 0. Post your list.', 'mental', 3, false, false, true),
('Name 15 animals in under 30 seconds', 'Set a timer. Write as many as you can. Post your list and time.', 'mental', 1, false, false, true),
('Write down the single thing you''ve been avoiding most', 'Be honest. Just one thing. Write what it is and why you''ve avoided it. Post it (you don''t have to do it today).', 'mental', 2, false, false, true),
('List 10 things you could do with a paperclip', 'Get creative. Practical, absurd, anything. Post all 10.', 'mental', 1, false, false, true),
('Write a pros and cons list for a decision you''re facing', 'Pick any real decision. At least 4 pros and 4 cons. Post it.', 'mental', 2, false, false, true),
('Recall the last dream you had in as much detail as possible', 'Whatever you can remember, write it down. Post it.', 'mental', 1, false, false, true),
('Write 3 things you would do with an extra hour today', 'Be realistic. Not "solve world hunger" — what would you actually do. Post it.', 'mental', 1, false, false, true),
('Calculate 15% tip on 5 different meal amounts in your head', 'Make up 5 totals and calculate the tip without a calculator. Post your answers.', 'mental', 2, false, false, true),
('Write down 5 things you know to be true about yourself', 'Not aspirational — actually, currently true. Post them.', 'mental', 2, false, false, true),
('Name the capital cities of 10 countries', 'Any 10. Write them down. No cheating. Post your list.', 'mental', 2, false, false, true),
('Write a letter to yourself 1 year from now', 'What do you want future-you to know? At least 5 sentences. Post it.', 'mental', 2, false, false, true),
('List every US president you can name in 2 minutes', 'Set a timer. Write them all. Post your count and list.', 'mental', 2, false, false, true),
('Write down your top 3 values and explain why', 'Not generic values — YOUR actual values. Why specifically? Post it.', 'mental', 2, false, false, true),

-- WILD (15 challenges)
('Do your best impression of a famous person on video', 'Commit to it. No half-assing. Video it.', 'wild', 2, false, true, false),
('Find something yellow within 30 feet', 'Right now. Without moving more than 30 feet. Photo it.', 'wild', 1, true, false, false),
('Eat something weird from your fridge', 'Combination, condiment, whatever. Document it. Photo or video.', 'wild', 3, true, false, false),
('Sing the first verse of any song you know', 'By yourself, unaccompanied. Full commitment. Video it.', 'wild', 3, false, true, false),
('Find an object shaped like a letter of the alphabet', 'Natural shapes only — not printed letters. Photo it and tell us which letter.', 'wild', 1, true, false, false),
('Make the best paper airplane you can and test it', 'Fold it. Launch it. Video the flight. Post distance estimate.', 'wild', 1, false, true, false),
('Describe your current vibe using only 5 emojis', 'No words. Just 5 emojis that capture your current energy. Post them.', 'wild', 1, false, false, true),
('Find something that''s been broken or needs fixing in your space', 'Not a philosophical metaphor. Something physically broken. Photo it.', 'wild', 1, true, false, false),
('Do a dramatic reading of any text near you', 'Terms and conditions, a label, a receipt — read it dramatically on video.', 'wild', 2, false, true, false),
('Find the oldest item in your home and photo it', 'Dig around. Find the oldest thing. Photo it and tell us what it is.', 'wild', 2, true, false, true),
('Make the most aesthetic photo of something normally ugly', 'Garbage, a drain, a utility box — find something ugly and make it beautiful.', 'wild', 3, true, false, false),
('Find something that starts with each letter of your first name', 'One object per letter. Line them up. Photo them all together.', 'wild', 2, true, false, false),
('Act out a scene from a movie completely silently on video', 'No sound. Mime the scene. Don''t tell us what movie it is — make us guess.', 'wild', 3, false, true, false),
('Find the exact color of your mood today in your surroundings', 'Find an object with a color that matches your mood. Photo it and explain why.', 'wild', 1, true, false, true),
('Do something you''ve never done before in the next 15 minutes', 'Anything new. Big or small. Post what you did and how it went.', 'wild', 2, true, false, true);
