import type { Post, UserEvent, DailyEvent, Challenge, Profile, ChallengeType, UserEventStatus } from '../types/database';

export const DEMO_CHALLENGES: Record<ChallengeType, Challenge> = {
  photo: {
    id: 'demo-challenge-photo',
    title: 'Show Us Your World',
    description: "Share a photo of what you're looking at right now.",
    type: 'photo',
    emoji: '📸',
    category: 'wild',
    difficulty: 2,
    xp_reward: 25,
    participant_count: 0,
    requires_photo: true,
    requires_video: false,
    requires_text: false,
    answer_rule: null,
    is_active: false,
    is_demo: true,
    schedule_count: 0,
    created_at: '2024-01-01T00:00:00.000Z',
  },
  poll: {
    // Uses the seeded DB challenge ID so PollResultCard can fetch real option data
    id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    title: 'Coffee or Tea?',
    description: 'Which do you prefer to start your morning?',
    type: 'poll',
    emoji: '☕',
    category: 'social',
    difficulty: 1,
    xp_reward: 25,
    participant_count: 0,
    requires_photo: false,
    requires_video: false,
    requires_text: false,
    answer_rule: null,
    is_active: false,
    is_demo: true,
    schedule_count: 0,
    created_at: '2024-01-01T00:00:00.000Z',
  },
  task: {
    id: 'demo-challenge-task',
    title: 'Describe Your Day',
    description: 'In one sentence, how would you describe today so far?',
    type: 'task',
    emoji: '📝',
    category: 'mental',
    difficulty: 1,
    xp_reward: 25,
    participant_count: 0,
    requires_photo: false,
    requires_video: false,
    requires_text: true,
    answer_rule: null,
    is_active: false,
    is_demo: true,
    schedule_count: 0,
    created_at: '2024-01-01T00:00:00.000Z',
  },
  format: {
    id: 'demo-challenge-format',
    title: 'Two Sentence Story',
    description: 'Write a two-sentence story about your morning.',
    type: 'format',
    emoji: '✍️',
    category: 'creative',
    difficulty: 2,
    xp_reward: 25,
    participant_count: 0,
    requires_photo: false,
    requires_video: false,
    requires_text: true,
    answer_rule: { type: 'starts_with_letter', letter: 'T' },
    is_active: false,
    is_demo: true,
    schedule_count: 0,
    created_at: '2024-01-01T00:00:00.000Z',
  },
};

export function makeDemoUserEvent(type: ChallengeType, status: UserEventStatus = 'pending'): UserEvent {
  const challenge = DEMO_CHALLENGES[type];
  const dailyEvent: DailyEvent = {
    id: `demo-daily-event-${type}`,
    challenge_id: challenge.id,
    fires_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    window_minutes: 999999,
    push_sent_at: null,
    created_at: new Date().toISOString(),
    challenge,
  };
  return {
    id: `demo-user-event-${type}`,
    user_id: 'demo-user',
    daily_event_id: dailyEvent.id,
    status,
    notified_at: null,
    completed_at: status === 'completed' ? new Date().toISOString() : null,
    expires_at: '2099-01-01T00:00:00.000Z',
    buy_in_at: null,
    streak_before_miss: null,
    signup_day_grace: false,
    created_at: new Date().toISOString(),
    daily_event: dailyEvent,
    challenge,
  };
}

function fakeProfile(username: string, displayName: string, gradient: [string, string]): Profile {
  return {
    id: `demo-profile-${username}`,
    username,
    display_name: displayName,
    avatar_url: null,
    avatar_gradient: gradient,
    bio: null,
    current_streak: 7,
    longest_streak: 30,
    total_completions: 42,
    total_missed: 3,
    xp: 1250,
    level: 5,
    reactions_received: 89,
    streak_shields: 1,
    notification_token: null,
    app_theme: 'dark',
    sparks: 820,
    accent_theme: 'default',
    appearance_mode: 'dark',
    equipped_border_key: null,
    equipped_title_key: null,
    timezone: 'America/Los_Angeles',
    is_admin: false,
    is_demo_account: false,
    onboarding_completed_at: '2024-01-01T00:00:00.000Z',
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: new Date().toISOString(),
  };
}

const now = Date.now();

export const DEMO_FEED_POSTS: Post[] = [
  {
    id: 'demo-feed-photo',
    user_event_id: null,
    user_id: 'demo-profile-jordan_k',
    type: 'photo',
    caption: 'My morning setup — finally got the lighting right 📸',
    photo_url: 'https://picsum.photos/seed/doji-demo-photo/600/600',
    front_photo_url: null,
    video_url: null,
    is_late: false,
    selected_option_index: null,
    reaction_count: 26,
    comment_count: 0,
    comments_disabled: false,
    visibility: 'friends',
    created_at: new Date(now - 22 * 60 * 1000).toISOString(),
    reaction_breakdown: { fire: 14, heart: 9, wow: 3 } as any,
    my_reactions: [],
    profile: fakeProfile('jordan_k', 'Jordan K.', ['#FF6B35', '#F7C59F']),
    challenge: DEMO_CHALLENGES.photo,
  },
  {
    id: 'demo-feed-poll',
    user_event_id: null,
    user_id: 'demo-profile-alex_m',
    type: 'poll_vote',
    caption: null,
    photo_url: null,
    front_photo_url: null,
    video_url: null,
    is_late: false,
    selected_option_index: 0,
    reaction_count: 30,
    comment_count: 0,
    comments_disabled: false,
    visibility: 'friends',
    created_at: new Date(now - 18 * 60 * 1000).toISOString(),
    reaction_breakdown: { fire: 22, like: 8 } as any,
    my_reactions: [],
    profile: fakeProfile('alex_m', 'Alex M.', ['#4776E6', '#8E54E9']),
    challenge: DEMO_CHALLENGES.poll,
  },
  {
    id: 'demo-feed-task',
    user_event_id: null,
    user_id: 'demo-profile-sam_r',
    type: 'task_complete',
    caption: 'Productive chaos. Three meetings, one good idea, two cold coffees. Somehow still smiling.',
    photo_url: null,
    front_photo_url: null,
    video_url: null,
    is_late: false,
    selected_option_index: null,
    reaction_count: 22,
    comment_count: 0,
    comments_disabled: false,
    visibility: 'friends',
    created_at: new Date(now - 12 * 60 * 1000).toISOString(),
    reaction_breakdown: { heart: 11, like: 7, fire: 4 } as any,
    my_reactions: [],
    profile: fakeProfile('sam_r', 'Sam R.', ['#11998e', '#38ef7d']),
    challenge: DEMO_CHALLENGES.task,
  },
  {
    id: 'demo-feed-format',
    user_event_id: null,
    user_id: 'demo-profile-mia_t',
    type: 'task_complete',
    caption:
      'She checked her phone one last time before bed. The notification could wait — it already had for three years.',
    photo_url: null,
    front_photo_url: null,
    video_url: null,
    is_late: false,
    selected_option_index: null,
    reaction_count: 36,
    comment_count: 0,
    comments_disabled: false,
    visibility: 'friends',
    created_at: new Date(now - 8 * 60 * 1000).toISOString(),
    reaction_breakdown: { fire: 18, wow: 12, heart: 6 } as any,
    my_reactions: [],
    profile: fakeProfile('mia_t', 'Mia T.', ['#f953c6', '#b91d73']),
    challenge: DEMO_CHALLENGES.format,
  },
];
