// Generated by scripts/sync-safety-taxonomy.mts; do not hand edit.
window.DojiReportTaxonomy = [
  {
    "value": "bullying_harassment",
    "label": "Bullying or unwanted contact",
    "details": [
      {
        "value": "bullying",
        "label": "Bullying or harassment",
        "restricted": false
      },
      {
        "value": "unwanted_contact",
        "label": "Repeated unwanted contact",
        "restricted": false
      },
      {
        "value": "sexual_harassment",
        "label": "Sexual harassment",
        "restricted": false
      },
      {
        "value": "threatening_private_content",
        "label": "Threatening to share private content",
        "restricted": false
      }
    ]
  },
  {
    "value": "self_harm",
    "label": "Suicide, self-harm or eating disorders",
    "details": [
      {
        "value": "suicide_self_harm",
        "label": "Suicide or self-harm",
        "restricted": false
      },
      {
        "value": "eating_disorder",
        "label": "Eating disorder content",
        "restricted": false
      }
    ]
  },
  {
    "value": "violence_hate_exploitation",
    "label": "Violence, hate or exploitation",
    "details": [
      {
        "value": "credible_threat",
        "label": "A credible threat or immediate danger",
        "restricted": true
      },
      {
        "value": "graphic_violence",
        "label": "Graphic or glorified violence",
        "restricted": false
      },
      {
        "value": "hate_speech",
        "label": "Hate speech or symbols",
        "restricted": false
      },
      {
        "value": "human_exploitation",
        "label": "Human exploitation or trafficking",
        "restricted": true
      },
      {
        "value": "animal_abuse",
        "label": "Animal abuse",
        "restricted": false
      }
    ]
  },
  {
    "value": "restricted_goods",
    "label": "Selling or promoting restricted items",
    "targets": [
      "post",
      "comment",
      "poll_response",
      "account"
    ],
    "details": [
      {
        "value": "drugs",
        "label": "Drugs",
        "restricted": false
      },
      {
        "value": "weapons",
        "label": "Weapons",
        "restricted": false
      },
      {
        "value": "animals",
        "label": "Animals",
        "restricted": false
      },
      {
        "value": "gambling",
        "label": "Gambling",
        "restricted": false
      },
      {
        "value": "alcohol_tobacco",
        "label": "Alcohol or tobacco",
        "restricted": false
      }
    ]
  },
  {
    "value": "sexual_content",
    "label": "Nudity or sexual activity",
    "details": [
      {
        "value": "nonconsensual_intimate_images",
        "label": "Threatening to share or sharing intimate images",
        "restricted": true
      },
      {
        "value": "sexual_solicitation",
        "label": "Sexual solicitation or prostitution",
        "restricted": false
      },
      {
        "value": "sexual_exploitation",
        "label": "Sexual exploitation",
        "restricted": true
      },
      {
        "value": "child_sexual_content",
        "label": "Sexual content involving a child",
        "restricted": true
      },
      {
        "value": "adult_nudity_or_sexual_activity",
        "label": "Adult nudity or sexual activity",
        "restricted": false
      }
    ]
  },
  {
    "value": "spam_scam",
    "label": "Scam, fraud or spam",
    "details": [
      {
        "value": "spam",
        "label": "Spam",
        "restricted": false
      },
      {
        "value": "scam_fraud",
        "label": "Scam or fraud",
        "restricted": false
      },
      {
        "value": "deceptive_business",
        "label": "Deceptive business or promotion",
        "restricted": false
      }
    ]
  },
  {
    "value": "intellectual_property",
    "label": "Intellectual property",
    "targets": [
      "post",
      "comment",
      "poll_response",
      "profile_photo"
    ],
    "details": [
      {
        "value": "copyright",
        "label": "Copyright infringement",
        "restricted": false
      },
      {
        "value": "trademark",
        "label": "Trademark infringement",
        "restricted": false
      },
      {
        "value": "counterfeit_goods",
        "label": "Counterfeit goods",
        "restricted": false
      }
    ]
  },
  {
    "value": "privacy",
    "label": "Privacy or personal information",
    "details": [
      {
        "value": "personal_information",
        "label": "Personal information",
        "restricted": false
      },
      {
        "value": "doxxing",
        "label": "Doxxing or exposing someone’s location",
        "restricted": false
      },
      {
        "value": "image_used_without_permission",
        "label": "An image used without permission",
        "restricted": false
      }
    ]
  },
  {
    "value": "impersonation",
    "label": "Impersonation",
    "targets": [
      "account"
    ],
    "details": [
      {
        "value": "impersonating_me",
        "label": "They’re pretending to be me",
        "restricted": false
      },
      {
        "value": "impersonating_someone_else",
        "label": "They’re pretending to be someone else",
        "restricted": false
      },
      {
        "value": "impersonating_business",
        "label": "They’re pretending to be a business",
        "restricted": false
      }
    ]
  },
  {
    "value": "other",
    "label": "Something else",
    "details": [
      {
        "value": "other",
        "label": "Something else",
        "restricted": false
      }
    ]
  }
];
