import { must } from "../../test-contracts.mts";
import {test,expect,reloadWithCoverage} from '../../coverage-fixture.mts';
import AxeBuilder from '@axe-core/playwright';
import type {Page} from '@playwright/test';
import {present,record} from '../../test-values.mts';
async function open(page:Page){
  await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
  await page.goto('/business-portal/');
  await page.getByRole('button',{name:'Open example workspace',exact:true}).click();
}
async function pick(page:Page,label:string,value:string){await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name:value,exact:true}).click();}
async function campaign(page:Page){
  await page.locator('[data-action="new-campaign"]').first().click();
  await page.getByLabel('Campaign name',{exact:true}).fill('Local review');
  await pick(page,'Campaign goal','Brand awareness');
  await page.getByLabel('Campaign start',{exact:true}).fill('2026-11-01');
  await page.getByLabel('Campaign end',{exact:true}).fill('2026-11-30');
  await page.getByLabel('Campaign brief',{exact:true}).fill('Synthetic local journey only.');
  await page.locator('#campaignForm').getByRole('button',{name:'Create campaign',exact:true}).click();
}
test('requested revision preserves exact four choices and prior submission locally',async({page})=>{
  await open(page);await page.locator('#overviewCampaigns [data-campaign-id="CAM-102"]').click();
  await page.locator('[data-business-doji="DOJI-102-A"]').click();
  await expect(page.locator('#businessDojiBody')).toContainText('Example feedback');
  await page.getByRole('button',{name:'Revise Doji',exact:true}).click();
  await expect(page.getByLabel('Choice 4',{exact:true})).toHaveValue('Fast finish');
  await page.getByLabel('Participant prompt').fill('Which kind of outdoor time do you enjoy?');
  await page.getByRole('button',{name:'Submit Doji for review',exact:true}).click();
  await page.locator('[data-business-doji="DOJI-102-A"]').click();
  await expect(page.locator('#editBusinessDoji')).toBeHidden();
  const stored:unknown=await page.evaluate(()=>JSON.parse(localStorage.getItem('doji-business-prototype-sample-campaigns-v3')||'null'));
  expect(Array.isArray(stored)).toBe(true);if(!Array.isArray(stored))throw Error('Missing saved campaigns');
  const saved=record(stored.find((c:unknown)=>record(c).id==='CAM-102'));
  expect(Array.isArray(saved.dojis)).toBe(true);if(!Array.isArray(saved.dojis))throw Error('Missing saved Dojis');
  const doji=record(saved.dojis.find((d:unknown)=>record(d).id==='DOJI-102-A'));
  expect(doji.options).toEqual(['Quiet reset','Big climb','Social miles','Fast finish','Other']);
  if(!Array.isArray(doji.previousSubmissions))throw Error('Missing previous submissions');
  expect(record(doji.previousSubmissions[0]).prompt).toBe('Which trail mood are you today?');
  expect(doji.revision).toBe(2);
});
test('save and edit exact draft without duplicates; format rule survives; submitted record is readonly',async({page})=>{
  const writes:string[]=[];page.on('request',r=>{if(r.method()==='POST')writes.push(r.url());});
  await open(page);await campaign(page);
  await page.getByLabel('Internal Doji name').fill('Two word answer');
  await pick(page,'Doji format','Format question');
  await page.getByLabel('Participant prompt').fill('Describe your ideal morning.');
  await page.getByLabel('Word count',{exact:true}).fill('2');
  await page.getByLabel('Requested live date').fill('2026-11-12');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await page.locator('[data-business-doji]').click();
  await expect(page.locator('#businessDojiBody')).toContainText('Answer format');
  await expect(page.locator('#businessDojiBody textarea').nth(3)).toHaveValue('Exactly 2 words');
  await page.getByRole('button',{name:'Edit draft',exact:true}).click();
  await expect(page.getByLabel('Word count',{exact:true})).toHaveValue('2');
  await page.getByLabel('Word count',{exact:true}).fill('3');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.locator('[data-business-doji]')).toHaveCount(1);
  await page.locator('[data-business-doji]').click();
  await page.getByRole('button',{name:'Edit draft',exact:true}).click();
  await page.getByRole('button',{name:'Submit Doji for review',exact:true}).click();
  await page.locator('[data-business-doji]').click();
  await expect(page.locator('#editBusinessDoji')).toBeHidden();
  await expect(page.locator('#businessDojiStatus')).toContainText('In review');
  await reloadWithCoverage(page);await page.getByRole('button',{name:'Open example workspace',exact:true}).click();
  await page.locator('#overviewCampaigns [data-campaign-id]').filter({hasText:'Local review'}).click();
  await expect(page.locator('[data-business-doji]')).toHaveCount(1);
  expect(writes).toEqual([]);
});
test('onboarding save resumes after reload; new workspace has no sample delivery charts',async({page})=>{
  await page.goto('/business-portal/');await page.getByRole('tab',{name:'Create account'}).click();
  await page.getByLabel('Your name').fill('Test Owner');await page.getByLabel('Work email').fill('owner@example.test');
  await page.getByRole('button',{name:'Start local setup'}).click();
  await page.getByLabel('Public company name').fill('Local company');
  await page.getByLabel('Legal company name').fill('Local Company Ltd');
  await page.getByLabel('Company website').fill('https://example.test');
  await page.getByLabel('Tell us about your business').fill('Synthetic local company.');
  await page.getByRole('button',{name:'Save and finish later'}).click();
  await reloadWithCoverage(page);await page.getByRole('button',{name:'Resume local workspace'}).click();
  await expect(page.getByLabel('Public company name')).toHaveValue('Local company');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  for(const [label,value] of [['Industry','Technology'],['Company size','1–10 employees'],['Headquarters','Canada'],['Primary goal','Brand awareness']] as const) await pick(page,label,value);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.locator('#businessAccuracy').check();await page.getByRole('button',{name:'Finish setup'}).click();
  await page.locator('.portalNav [data-view="analytics"]').click();
  await expect(page.locator('#analyticsSampleBanner')).toContainText('No results yet');
  await expect(page.locator('.analyticsGrid')).toBeHidden();
  await expect(page.locator('#resultsMetrics')).toBeHidden();
});
test('invalid choices and links remain visible without saving; custom dropdown uses keyboard',async({page})=>{
  await open(page);await campaign(page);
  const format=page.getByRole('combobox',{name:'Doji format',exact:true});
  await format.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Escape');
  await expect(page.locator('#dojiModal')).toBeVisible();
  await page.getByLabel('Internal Doji name').fill('Poll');await page.getByLabel('Participant prompt').fill('Pick one.');
  await page.getByLabel('Requested live date').fill('2026-11-12');
  await page.getByRole('button',{name:'Submit Doji for review',exact:true}).click();
  await expect(page.locator('#dojiForm .businessFormError')).toContainText('Complete every choice');
  await page.getByLabel('Choice 1',{exact:true}).fill('Same');await page.getByLabel('Choice 2',{exact:true}).fill('Same');
  await page.getByRole('button',{name:'Submit Doji for review',exact:true}).click();
  await expect(page.locator('#dojiForm .businessFormError')).toContainText('distinct');
  await page.getByLabel('Choice 2',{exact:true}).fill('Different');
  await page.getByLabel('Optional Learn more link').fill('http://example.test');
  await page.getByRole('button',{name:'Submit Doji for review',exact:true}).click();
  await expect(page.locator('#dojiForm .businessFormError')).toContainText('HTTPS');
});
for(const width of [390,1440])for(const theme of ['light','dark'])test(`shared business drawers and forms ${theme} ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:950});await open(page);
  await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);
  await page.locator('#overviewCampaigns [data-campaign-id="CAM-102"]').click();
  const dialog=page.locator('#campaignDetailModal');
  const rect=present(must(await dialog.boundingBox()));expect(rect.x+rect.width).toBeCloseTo(width,0);expect(rect.y).toBe(0);
  await page.screenshot({path:info.outputPath('campaign.png')});
  await page.locator('[data-business-doji="DOJI-102-B"]').click();
  await expect(page.locator('#businessDojiDetail')).toBeVisible();
  await page.getByRole('button',{name:'Edit draft',exact:true}).click();
  await pick(page,'Doji format','Format question');
  await page.screenshot({path:info.outputPath('form.png')});
  const result=await new AxeBuilder({page}).include('#dojiModal').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(result.violations).toEqual([]);
  expect(await page.evaluate(()=>document.body.scrollWidth)).toBeLessThanOrEqual(width+1);
});
