// Derive the external form and SQL allowlist from the existing member taxonomy.
// --write is a mechanical regeneration; default is a drift check.
import {readFileSync, writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import ts from 'typescript';
import { evidenceRecord, evidenceStrings } from './release-evidence.mts';
import type { SafetyCategory } from '../website/safety-removal/contracts.d.mts';
// The member package uses Babel's module pipeline, not NodeNext. Read its
// compiler output in an isolated VM; validate that boundary without changing
// the member package's module mode to accommodate an offline generator.
const exported: Record<string,unknown>={};
vm.runInNewContext(ts.transpileModule(readFileSync('lib/reportingTaxonomy.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:exported});
assert.ok(Array.isArray(exported.REPORT_REASON_OPTIONS));
const detailMap=evidenceRecord(exported.REPORT_REASON_DETAILS), restricted=exported.isRestrictedSafetyDetail;
assert.ok(typeof restricted==='function');
const catalog: SafetyCategory[]=exported.REPORT_REASON_OPTIONS.map(value=>{
 const reason=evidenceRecord(value);assert.ok(typeof reason.value==='string'&&typeof reason.label==='string');
 const details=detailMap[reason.value];assert.ok(Array.isArray(details));
 return {value:reason.value,label:reason.label,...(reason.targets===undefined?{}:{targets:evidenceStrings(reason.targets)}),details:details.map(value=>{
  const detail=evidenceRecord(value);assert.ok(typeof detail.value==='string'&&typeof detail.label==='string');
  const result: unknown=restricted(detail.value);assert.ok(typeof result==='boolean');
  return {value:detail.value,label:detail.label,restricted:result};
 })};
});
const source=`// Generated by scripts/sync-safety-taxonomy.mts; do not hand edit.\nwindow.DojiReportTaxonomy = ${JSON.stringify(catalog,null,2)};\n`;
const quote=(v: string)=>`'${v.replaceAll("'","''")}'`;
const rows=catalog.flatMap(r=>r.details.map(d=>`(${quote(r.value)},${quote(d.value)},${quote(r.label)},${quote(d.label)},${d.restricted},array[${(r.targets||['post','comment','poll_response','profile_photo','account']).map(quote).join(',')}]::text[])`));
const sql=`-- BEGIN GENERATED SAFETY TAXONOMY\ncreate function public.safety_removal_taxonomy_v1()\nreturns table(reason text, detail text, reason_label text, detail_label text, restricted boolean, targets text[])\nlanguage sql immutable security definer set search_path='' as $$\n values ${rows.join(',\n ')}\n$$;\nrevoke all on function public.safety_removal_taxonomy_v1() from public,anon,authenticated,doji_employee,service_role;\n-- END GENERATED SAFETY TAXONOMY`;
const path='docs/drafts/external_takedown_intake_v1.sql', original=readFileSync(path,'utf8');
assert.ok(original.includes('-- BEGIN GENERATED SAFETY TAXONOMY') && original.includes('-- END GENERATED SAFETY TAXONOMY'),'Missing taxonomy marker');
const updated=original.replace(/-- BEGIN GENERATED SAFETY TAXONOMY[\s\S]*?-- END GENERATED SAFETY TAXONOMY/,()=>sql);
for(const [file,value] of [['website/safety-removal/taxonomy.mts',source],[path,updated]] as const) {
 if(process.argv.includes('--write'))writeFileSync(file,value);
 else assert.equal(readFileSync(file,'utf8'),value,`${file} taxonomy drift`);
}
console.log(`External taxonomy ${process.argv.includes('--write')?'generated':'verified'}: ${rows.length} leaves; member source unchanged.`);
