reset role;
set constraints auth.business_signup_agreement immediate;
update business_private.settings set enabled=true,application_terms_version='test-terms-v1',privacy_version='test-privacy-v1';
select pg_temp.check_true(not (select enabled from business_private.privacy_settings),'privacy workflow defaults off');
select pg_temp.expect_error('select public.get_admin_business_privacy_page_v1(''open'')','workflow disabled');
update business_private.privacy_settings set enabled=true;
select set_config('test.privacy.owner','79000000-0000-4000-8000-000000000001',true);
select pg_temp.expect_error($q$insert into auth.users(id,email,role,raw_app_meta_data) values('79000000-0000-4000-8000-000000000001','privacy@test.invalid','doji_business','{"account_type":"business"}')$q$,'signup agreement required');
select pg_temp.check_true(not exists(select 1 from auth.users where id=current_setting('test.privacy.owner')::uuid),'missing signup agreement rolls back account');
insert into auth.users(id,email,role,raw_app_meta_data,raw_user_meta_data,email_confirmed_at) values
 (current_setting('test.privacy.owner')::uuid,'privacy@test.invalid','doji_business',
 '{"account_type":"business","business_signup":{"terms_accepted":true,"privacy_acknowledged":true,"terms_version":"test-terms-v1","privacy_version":"test-privacy-v1"}}','{"display_name":"Privacy Owner"}',now());
select pg_temp.check_true((select terms_version='test-terms-v1' and privacy_version='test-privacy-v1' and accepted_at is not null from business_private.signup_agreements where account_id=current_setting('test.privacy.owner')::uuid),'signup agreement records exact versions and database timestamp');
select pg_temp.check_true(public.check_business_signup_legal_v1('test-terms-v1','test-privacy-v1'),'current legal precheck succeeds');
select pg_temp.check_true(not public.check_business_signup_legal_v1('stale','test-privacy-v1'),'stale legal precheck fails');
select pg_temp.check_true(not exists(select 1 from business_private.signup_agreements where account_id=current_setting('test.member')::uuid),'member never receives business agreement record');
select pg_temp.check_true(not has_function_privilege('authenticated','public.admin_business_privacy_open_v1(uuid,text,text,timestamptz,uuid)','execute'),'member privacy commands denied');
select pg_temp.check_true(not has_function_privilege('doji_business','public.get_admin_business_privacy_access_v1(uuid,bigint)','execute'),'business cannot access another account export');
select pg_temp.check_true(not has_function_privilege('anon','public.check_business_signup_legal_v1(text,text)','execute'),'anonymous cannot call service legal precheck');
select pg_temp.check_true(not has_function_privilege('doji_employee','public.claim_business_erasure_v1(uuid,uuid)','execute'),'employee cannot execute Auth deletion');
select pg_temp.check_true(not has_function_privilege('service_role','public.admin_business_privacy_command_v1(uuid,bigint,text,text,uuid,jsonb,bigint)','execute'),'service cannot approve erasure');
select pg_temp.check_true(not has_table_privilege('doji_employee','business_private.privacy_cases','select,insert,update,delete'),'employee cannot bypass case RPC');
select pg_temp.check_true(not exists(select 1 from unnest(array['anon','authenticated','doji_business','service_role']) r where has_function_privilege(r,'public.get_admin_business_privacy_correction_v1(uuid)','execute')),'correction reader excludes public, member, business and service roles');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.privacy.owner'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select set_config('test.privacy.app',public.business_application_command_v1('submit',null,current_setting('test.details')::jsonb-'business_address','test-terms-v1','test-privacy-v1',gen_random_uuid())#>>'{outcome,id}',true);
select pg_temp.check_true(public.get_business_application_v1()->>'state'='pending','complete application needs no street address');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal1')::text,true);
set local role doji_employee;
select pg_temp.expect_error('select public.get_admin_business_privacy_page_v1(''open'')','employee MFA required');
select pg_temp.expect_error('select public.get_admin_business_privacy_correction_v1(gen_random_uuid())','employee MFA required');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.expect_error('select public.get_admin_business_privacy_page_v1(''open'')','Restricted privacy permission');
select pg_temp.expect_error('select public.get_admin_business_privacy_correction_v1(gen_random_uuid())','Restricted privacy permission');
reset role;
update public.admin_employees set roles=array['super_admin'] where id=current_setting('test.employee')::uuid;
set local role doji_employee;
select pg_temp.expect_error($q$select public.admin_business_privacy_open_v1(current_setting('test.member')::uuid,'access','case:verified-member',now(),gen_random_uuid())$q$,'separate business identity');
select pg_temp.expect_error($q$select public.admin_business_privacy_open_v1(current_setting('test.employee')::uuid,'erasure','case:verified-employee',now(),gen_random_uuid())$q$,'separate business identity');
select pg_temp.expect_error($q$select public.admin_business_privacy_open_v1(current_setting('test.privacy.owner')::uuid,'access','name email@example.com',now(),gen_random_uuid())$q$,'opaque evidence reference');
select set_config('test.privacy.access',public.admin_business_privacy_open_v1(current_setting('test.privacy.owner')::uuid,'access','case:verified-access',now(),'79000000-0000-4000-8000-000000000010')->>'id',true);
select pg_temp.check_true(public.admin_business_privacy_open_v1(current_setting('test.privacy.owner')::uuid,'access','case:verified-access',now(),'79000000-0000-4000-8000-000000000010')->>'id'=current_setting('test.privacy.access'),'exact privacy request retry returns same case');
select pg_temp.expect_error($q$select public.admin_business_privacy_open_v1(current_setting('test.privacy.owner')::uuid,'erasure','case:verified-access',now(),'79000000-0000-4000-8000-000000000010')$q$,'different command');
select pg_temp.check_true(public.get_admin_business_privacy_access_v1(current_setting('test.privacy.access')::uuid)#>>'{identity,email}'='privacy@test.invalid','access export contains exact requester identity');
select pg_temp.check_true(public.get_admin_business_privacy_access_v1(current_setting('test.privacy.access')::uuid)::text not like '%internal_note%','access export excludes staff internal notes');
select pg_temp.check_true(jsonb_array_length(public.get_admin_business_privacy_page_v1('open'))=1,'bounded exact-state privacy queue');
select pg_temp.check_true(public.get_admin_business_privacy_case_v1(current_setting('test.privacy.access')::uuid)#>>'{history,0,action}'='received','exact privacy case exposes its bounded audit history');
select pg_temp.check_true(not (public.get_admin_business_privacy_case_v1(current_setting('test.privacy.access')::uuid)?'cleanup_email'),'case detail excludes temporary email cleanup key');
select set_config('test.privacy.closure',public.admin_business_privacy_open_v1(current_setting('test.other')::uuid,'closure','case:verified-closure',now(),gen_random_uuid())->>'id',true);
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.closure')::uuid,1,'complete','case:closure-complete',gen_random_uuid())$q$,'Close account before completion');
select public.admin_business_privacy_command_v1(current_setting('test.privacy.closure')::uuid,1,'close_account','case:closure-authorized',gen_random_uuid());
reset role;
select pg_temp.check_true((select disabled from business_private.accounts where id=current_setting('test.other')::uuid),'closure disables only the target business');
select pg_temp.check_true(exists(select 1 from auth.users where id=current_setting('test.other')::uuid),'closure is not Auth erasure');
set local role doji_employee;
select set_config('test.privacy.correction',public.admin_business_privacy_open_v1(current_setting('test.privacy.owner')::uuid,'correction','case:verified-correction',now(),gen_random_uuid())->>'id',true);
select pg_temp.expect_error('select public.get_admin_business_privacy_correction_v1(gen_random_uuid())','Open verified correction');
select pg_temp.expect_error('select public.get_admin_business_privacy_correction_v1(current_setting(''test.privacy.access'')::uuid)','Open verified correction');
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)->>'blocked_reason'='review_required','pending submitted application cannot be edited as a draft');
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.correction')::uuid,1,'correct_draft','case:correction-approval',gen_random_uuid(),'{}',1)$q$,'Reopen through business review');
select public.admin_business_application_command_v1(current_setting('test.privacy.app')::uuid,1,'request_changes','Please confirm the corrected application.','Synthetic privacy correction review.',gen_random_uuid());
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)#>>'{application,revision}'='2','correction reader returns exact current application revision');
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)->>'account_id'=current_setting('test.privacy.owner'),'correction reader binds exact business account from verified case');
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)->>'correction_allowed'='true','requested-changes application is editable');
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.correction')::uuid,1,'correct_draft','case:stale-correction',gen_random_uuid(),current_setting('test.details')::jsonb,1)$q$,'Application changed');
select public.admin_business_privacy_command_v1(current_setting('test.privacy.correction')::uuid,1,'correct_draft','case:correction-approval',gen_random_uuid(),current_setting('test.details')::jsonb||'{"brand_name":"Corrected Brand"}',2);
reset role;
select pg_temp.check_true((select details->>'brand_name'='Corrected Brand' from business_private.applications where id=current_setting('test.privacy.app')::uuid),'correction updates editable draft');
select pg_temp.check_true((select details->>'brand_name'='Example' from business_private.submissions where application_id=current_setting('test.privacy.app')::uuid),'correction preserves immutable submitted snapshot');
set local role doji_employee;
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)#>>'{application,details,brand_name}'='Corrected Brand','correction read exposes current draft, not unchanged original snapshot');
select pg_temp.check_true(public.get_admin_business_privacy_case_v1(current_setting('test.privacy.correction')::uuid)->>'revision'='2','repeated correction reads do not mutate case revision');
select pg_temp.check_true(not (public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)::text ~ 'internal_note|encrypted_password|email'),'correction read excludes Auth identity, credentials and internal notes');
reset role;
-- Deliberately corrupt only this rollback fixture to prove exact identity defense.
insert into business_private.accounts(id) values(current_setting('test.member')::uuid) on conflict do nothing;
update business_private.privacy_cases set account_id=current_setting('test.member')::uuid where id=current_setting('test.privacy.correction')::uuid;
set local role doji_employee;
select pg_temp.expect_error('select public.get_admin_business_privacy_correction_v1(current_setting(''test.privacy.correction'')::uuid)','separate business identity');
reset role;
update business_private.privacy_cases set account_id=current_setting('test.privacy.owner')::uuid,state='denied' where id=current_setting('test.privacy.correction')::uuid;
set local role doji_employee;
select pg_temp.expect_error('select public.get_admin_business_privacy_correction_v1(current_setting(''test.privacy.correction'')::uuid)','Open verified correction');
reset role;
update business_private.privacy_cases set state='open' where id=current_setting('test.privacy.correction')::uuid;
insert into auth.users(id,email,role,raw_app_meta_data,email_confirmed_at) values('79000000-0000-4000-8000-000000000030','privacy-empty@test.invalid','doji_business','{"account_type":"business","business_signup":{"terms_accepted":true,"privacy_acknowledged":true,"terms_version":"test-terms-v1","privacy_version":"test-privacy-v1"}}',now());
set local role doji_employee;
select set_config('test.privacy.empty',public.admin_business_privacy_open_v1('79000000-0000-4000-8000-000000000030','correction','case:verified-empty',now(),gen_random_uuid())->>'id',true);
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.empty')::uuid)->>'blocked_reason'='no_application','missing draft cannot be inferred or fabricated');
select set_config('test.privacy.erase',public.admin_business_privacy_open_v1(current_setting('test.privacy.owner')::uuid,'erasure','case:verified-erasure',now(),gen_random_uuid())->>'id',true);
select public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,1,'hold','legal:hold-0001',gen_random_uuid());
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)->>'correction_allowed'='true','hold preserves snapshots but does not invent a restriction on permitted draft corrections');
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.access')::uuid,1,'release_hold','legal:wrong-case',gen_random_uuid())$q$,'original case');
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.access')::uuid,1,'hold','legal:replace-hold',gen_random_uuid())$q$,'Existing hold');
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,2,'prepare_erasure','case:erase-authorized',gen_random_uuid())$q$,'Legal hold');
select public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,2,'release_hold','legal:release-0001',gen_random_uuid());
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,2,'prepare_erasure','case:erase-authorized',gen_random_uuid())$q$,'case changed');
select public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,3,'prepare_erasure','case:erase-authorized','79000000-0000-4000-8000-000000000011');
select pg_temp.check_true(public.get_admin_business_privacy_correction_v1(current_setting('test.privacy.correction')::uuid)->>'blocked_reason'='erasure_prepared','prepared erasure blocks current draft correction');
select pg_temp.check_true(public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,3,'prepare_erasure','case:erase-authorized','79000000-0000-4000-8000-000000000011')->>'revision'='4','erasure preparation replays without duplicate audit');
select pg_temp.expect_error($q$select public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,4,'complete','case:provider-reviewed',gen_random_uuid())$q$,'Primary erasure');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.privacy.owner'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.expect_error('select public.get_business_application_v1()','Business access disabled');
reset role;
set local role service_role;
select pg_temp.check_true(public.claim_business_erasure_v1(current_setting('test.privacy.erase')::uuid,'79000000-0000-4000-8000-000000000012')->>'delete_authorized'='true','exact approved erasure grants one Auth deletion');
select pg_temp.check_true(public.claim_business_erasure_v1(current_setting('test.privacy.erase')::uuid,'79000000-0000-4000-8000-000000000012')->>'delete_authorized'='false','execution retry reconciles but cannot blindly repeat Auth deletion');
select pg_temp.expect_error($q$select public.claim_business_erasure_v1(current_setting('test.privacy.erase')::uuid,gen_random_uuid())$q$,'Different erasure execution');
select pg_temp.expect_error($q$select public.finish_business_erasure_v1(current_setting('test.privacy.erase')::uuid,'79000000-0000-4000-8000-000000000012')$q$,'Auth deletion not confirmed');
reset role;
-- Synthetic database-only simulation; real Auth API path has separate integration test.
delete from auth.users where id=current_setting('test.privacy.owner')::uuid;
set local role service_role;
select pg_temp.check_true(public.finish_business_erasure_v1(current_setting('test.privacy.erase')::uuid,'79000000-0000-4000-8000-000000000012')->>'state'='primary_erased','primary erasure completes only after exact Auth absence');
select pg_temp.check_true(public.finish_business_erasure_v1(current_setting('test.privacy.erase')::uuid,'79000000-0000-4000-8000-000000000012')->>'state'='primary_erased','primary completion retry is idempotent');
reset role;
select pg_temp.check_true((select details='{}' and response='' from business_private.applications where id=current_setting('test.privacy.app')::uuid),'erasure removes current application content');
select pg_temp.check_true(not exists(select 1 from business_private.submissions where application_id=current_setting('test.privacy.app')::uuid and details<>'{}'),'erasure removes historical submission content');
select pg_temp.check_true(not exists(select 1 from business_private.history where application_id=current_setting('test.privacy.app')::uuid and (response<>'' or internal_note<>'')),'erasure removes business review notes');
select pg_temp.check_true((select cleanup_email is null from business_private.privacy_cases where id=current_setting('test.privacy.erase')::uuid),'erasure clears temporary email cleanup key');
select pg_temp.check_true(exists(select 1 from auth.users where id=current_setting('test.member')::uuid),'member identity survives business erasure');
select pg_temp.check_true(exists(select 1 from business_private.signup_agreements where account_id=current_setting('test.privacy.owner')::uuid),'minimal version evidence retained separately from erased content');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(public.admin_business_privacy_command_v1(current_setting('test.privacy.erase')::uuid,6,'complete','case:provider-backup-review',gen_random_uuid())->>'state'='completed','request completion requires separate provider and backup review reference');
reset role;
