create function pg_temp.ok(p boolean,label text) returns text language plpgsql as $$begin
 if p is distinct from true then raise exception 'FAIL: %',label; end if;return 'PASS: '||label;end$$;
create function pg_temp.denied(q text,label text,code text default '42501') returns text language plpgsql as $$begin
 begin execute q; exception when others then
  if sqlstate=code then return 'PASS: '||label;end if;raise;
 end;raise exception 'FAIL: expected denial %',label;end$$;
insert into portal_identity_private.realms(realm,enabled,issuer,audience) values
 ('business',true,'https://business.test','business-test'),('employee',true,'https://employee.test','employee-test');
update business_private.settings set enabled=true,application_terms_version='terms-v1',privacy_version='privacy-v1';
update business_private.privacy_settings set enabled=true;
update portal_identity_private.business_enrollment_settings set enabled=true,admission_until=now()+interval '1 hour',account_limit=2;
update portal_identity_private.business_read_settings set enabled=true;
update portal_identity_private.business_command_settings set enabled=true;
grant doji_identity_resolver,doji_business_enrollment,doji_employee,service_role to postgres;
set local role doji_business_enrollment;
select set_config('test.business.id',portal_identity_private.complete_business_enrollment(
 'https://business.test','business-test','user_independent','session_test',true,true,'terms-v1','privacy-v1','US')::text,true);
reset role;
select pg_temp.ok(not exists(select 1 from auth.users where id=current_setting('test.business.id')::uuid),'independent account has no Supabase Auth row');
select pg_temp.ok(portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'verified independent business is approval eligible');
select pg_temp.ok(not portal_identity_private.business_approval_eligible('91000000-0000-4000-8000-000000000001'),'member identity cannot become business');
select pg_temp.ok(not portal_identity_private.business_approval_eligible('91000000-0000-4000-8000-000000000003'),'employee identity cannot become business');
select pg_temp.ok(not portal_identity_private.business_approval_eligible(gen_random_uuid()),'unknown identity cannot become business');
select set_config('test.details','{"legal_name":"Example LLC","brand_name":"Example","website":"https://example.test","country":"US","representative_name":"Test Owner","representative_role":"Owner","category":"Retail","purpose":"Synthetic local verification"}',true);
set local role doji_identity_resolver;
select set_config('test.application.id',portal_identity_private.business_application_command(
 'https://business.test','business-test','user_independent','session_test',false,'submit',null,current_setting('test.details')::jsonb,'terms-v1','privacy-v1',gen_random_uuid())#>>'{outcome,id}',true);
reset role;
set local request.jwt.claims='{"sub":"91000000-0000-4000-8000-000000000003","role":"doji_employee","aal":"aal1"}';
set local role doji_employee;
select pg_temp.denied($q$select public.admin_business_application_command_v1(current_setting('test.application.id')::uuid,1,'approve','Application approved.','Synthetic reviewed business.',gen_random_uuid())$q$,'employee MFA remains required');
reset role;
set local request.jwt.claims='{"sub":"91000000-0000-4000-8000-000000000003","role":"doji_employee","aal":"aal2"}';
set local role doji_employee;
select pg_temp.ok(public.admin_business_application_command_v1(current_setting('test.application.id')::uuid,1,'approve','Application approved.','Synthetic reviewed business.','88000000-0000-4000-8000-000000000001')#>>'{outcome,state}'='approved','employee approves exact independent business');
select pg_temp.ok(public.admin_business_application_command_v1(current_setting('test.application.id')::uuid,1,'approve','Application approved.','Synthetic reviewed business.','88000000-0000-4000-8000-000000000001')->>'replayed'='true','review retry replays existing receipt');
reset role;
select pg_temp.ok((select count(*)=1 from business_private.organizations),'approval creates one organization');
select pg_temp.ok((select count(*)=1 from business_private.memberships),'approval creates one membership');
set local role doji_identity_resolver;
select pg_temp.ok(portal_identity_private.read_business_application('https://business.test','business-test','user_independent','session_test',false)->>'state'='approved','applicant sees approved state');
select pg_temp.denied($q$select portal_identity_private.read_business_workspace('https://business.test','business-test','user_independent','session_test',false)$q$,'approved workspace still requires MFA');
select pg_temp.ok(portal_identity_private.read_business_workspace('https://business.test','business-test','user_independent','session_test',true)->>'billing_enabled'='false','billing stays disabled');
select pg_temp.ok(portal_identity_private.read_business_workspace('https://business.test','business-test','user_independent','session_test',true)->>'campaigns_enabled'='false','campaign publishing stays disabled');
reset role;
set local role doji_employee;
select public.admin_business_application_command_v1(current_setting('test.application.id')::uuid,2,'reopen','Please correct details.','Synthetic reopening for correction.',gen_random_uuid());
reset role;
select pg_temp.denied($q$select portal_identity_private.read_business_workspace('https://business.test','business-test','user_independent','session_test',true)$q$,'reopening removes workspace authority');
set local role doji_employee;
select set_config('test.access.id',public.admin_business_privacy_open_v1(current_setting('test.business.id')::uuid,'access','case:verified-access',now(),gen_random_uuid())->>'id',true);
select pg_temp.ok(public.get_admin_business_privacy_access_v1(current_setting('test.access.id')::uuid)->>'identity_source'='workos_business','privacy access identifies exact independent directory');
select pg_temp.ok(public.get_admin_business_privacy_access_v1(current_setting('test.access.id')::uuid)->>'provider_export_required'='true','export cannot silently claim provider data complete');
select pg_temp.ok(public.get_admin_business_privacy_access_v1(current_setting('test.access.id')::uuid)->'identity'='null'::jsonb,'no legacy Auth identity substituted in export');
select set_config('test.correction.id',public.admin_business_privacy_open_v1(current_setting('test.business.id')::uuid,'correction','case:verified-correction',now(),gen_random_uuid())->>'id',true);
select pg_temp.ok(public.get_admin_business_privacy_correction_v1(current_setting('test.correction.id')::uuid)->>'correction_allowed'='true','verified independent correction case opens');
select public.admin_business_privacy_command_v1(current_setting('test.correction.id')::uuid,1,'correct_draft','case:corrected-draft',gen_random_uuid(),current_setting('test.details')::jsonb||'{"brand_name":"Corrected"}',3);
select pg_temp.ok(public.get_admin_business_privacy_correction_v1(current_setting('test.correction.id')::uuid)#>>'{application,details,brand_name}'='Corrected','exact current draft correction succeeds');
reset role;
select pg_temp.ok((select details->>'brand_name'='Example' from business_private.submissions),'correction preserves submitted evidence');
update portal_identity_private.identities set revoked=true where principal_id=current_setting('test.business.id')::uuid;
select pg_temp.ok(not portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'revoked mapping denies approval');
update portal_identity_private.identities set revoked=false;
update portal_identity_private.principals set state='disabled' where id=current_setting('test.business.id')::uuid;
select pg_temp.ok(not portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'disabled principal denies approval');
update portal_identity_private.principals set state='active' where id=current_setting('test.business.id')::uuid;
update portal_identity_private.principals set state='pending' where id=current_setting('test.business.id')::uuid;
select pg_temp.ok(not portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'pending principal is not a verified applicant');
update portal_identity_private.principals set state='deleted' where id=current_setting('test.business.id')::uuid;
select pg_temp.ok(not portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'deleted principal cannot be approved');
update portal_identity_private.principals set state='active' where id=current_setting('test.business.id')::uuid;
select portal_identity_private.bind_identity('employee','user_wrongrealm','88000000-0000-4000-8000-000000000003','synthetic-wrong-realm');
insert into business_private.accounts(id) values('88000000-0000-4000-8000-000000000003');
select pg_temp.denied($q$select business_private.privacy_target('88000000-0000-4000-8000-000000000003',true)$q$,'employee registry principal cannot become a business privacy target');
select pg_temp.ok(not portal_identity_private.business_approval_eligible('88000000-0000-4000-8000-000000000003'),'wrong-realm registry principal cannot be approved');
delete from business_private.accounts where id='88000000-0000-4000-8000-000000000003';
update portal_identity_private.realms set enabled=false where realm='business';
select pg_temp.ok(not portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'frozen directory denies approval');
set local role doji_employee;
select pg_temp.ok(public.get_admin_business_privacy_access_v1(current_setting('test.access.id')::uuid)->>'provider_export_required'='true','privacy work remains accessible while business login frozen');
reset role;
update portal_identity_private.realms set enabled=true where realm='business';
select pg_temp.denied($q$select business_private.privacy_target('91000000-0000-4000-8000-000000000001',true)$q$,'privacy does not target member');
select pg_temp.denied($q$select business_private.privacy_target('91000000-0000-4000-8000-000000000003',true)$q$,'privacy does not target employee');
set local role doji_employee;
select set_config('test.closure.id',public.admin_business_privacy_open_v1(current_setting('test.business.id')::uuid,'closure','case:verified-closure',now(),gen_random_uuid())->>'id',true);
select public.admin_business_privacy_command_v1(current_setting('test.closure.id')::uuid,1,'close_account','case:close-business',gen_random_uuid());
reset role;
select pg_temp.ok(not portal_identity_private.business_approval_eligible(current_setting('test.business.id')::uuid),'closed account denies approval');
select pg_temp.denied($q$select portal_identity_private.read_business_application('https://business.test','business-test','user_independent','session_test',false)$q$,'closure denies existing applicant session');
set local role doji_employee;
select set_config('test.erasure.id',public.admin_business_privacy_open_v1(current_setting('test.business.id')::uuid,'erasure','case:verified-erasure',now(),gen_random_uuid())->>'id',true);
select public.admin_business_privacy_command_v1(current_setting('test.erasure.id')::uuid,1,'prepare_erasure','case:prepare-erasure',gen_random_uuid());
reset role;
set local role service_role;
select pg_temp.denied($q$select public.claim_business_erasure_v1(current_setting('test.erasure.id')::uuid,gen_random_uuid())$q$,'legacy erasure executor cannot target WorkOS business');
reset role;
select pg_temp.ok((select state='prepared' from business_private.privacy_cases where id=current_setting('test.erasure.id')::uuid),'failed wrong-provider deletion leaves case prepared');
update business_private.privacy_cases set state='executing',execution_id='88000000-0000-4000-8000-000000000002' where id=current_setting('test.erasure.id')::uuid;
set local role service_role;
select pg_temp.denied($q$select public.finish_business_erasure_v1(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002')$q$,'missing Supabase user is not proof of WorkOS deletion');
reset role;
select pg_temp.ok((select details->>'brand_name'='Corrected' from business_private.applications),'wrong-provider finish cannot erase business data');
select pg_temp.ok(not exists(select 1 from unnest(array['anon','authenticated','doji_employee','doji_business','service_role','doji_identity_resolver','doji_business_enrollment']) r
 where has_function_privilege(r,'portal_identity_private.business_approval_eligible(uuid)','execute')),'internal eligibility helper not exposed to any API role');
select pg_temp.ok(not exists(select 1 from unnest(array['anon','authenticated','doji_employee','doji_business','service_role','doji_identity_resolver','doji_business_enrollment']) r
 where has_table_privilege(r,'portal_identity_private.business_review_restore','select,insert,update,delete')),'rollback definitions not exposed');
