create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin
 if ok is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end$$;
create function pg_temp.expect_error(command text,fragment text) returns void language plpgsql as $$begin
 begin execute command; exception when others then if position(fragment in sqlerrm)>0 then return; end if; raise; end;
 raise exception 'FAIL: expected %',fragment; end$$;
select set_config('test.employee',id::text,true) from public.admin_employees where 'super_admin'=any(roles) limit 1;
select pg_temp.check_true(length(current_setting('test.employee'))=36,'synthetic employee available');
select set_config('test.request','{"name":"Synthetic requester","contact":"test@test.invalid","relationship":"depicted","reason":"sexual_content","detail":"nonconsensual_intimate_images","location":"Synthetic content reference","statement":"Shared without my permission","signature":"Synthetic requester","consent":true}',true);
select set_config('test.case','aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee',true);
select set_config('test.secret',repeat('a',64),true);
select set_config('request.jwt.claims','{"role":"service_role"}',true);
set local role service_role;
select pg_temp.check_true(not has_table_privilege(current_user,'public.safety_removal_cases','SELECT'),'service cannot browse raw private requests');
select public.submit_safety_removal_v1(current_setting('test.case')::uuid,current_setting('test.secret'),current_setting('test.request')::jsonb);
select public.submit_safety_removal_v1(current_setting('test.case')::uuid,current_setting('test.secret'),current_setting('test.request')::jsonb);
select pg_temp.expect_error(format('select public.submit_safety_removal_v1(%L,%L,%L)',current_setting('test.case'),repeat('b',64),current_setting('test.request')),'reference already used');
select pg_temp.expect_error(format('select public.submit_safety_removal_v1(%L,%L,%L)',current_setting('test.case'),current_setting('test.secret'),(current_setting('test.request')::jsonb||'{"signature":"different"}')::text),'reference already used');
select pg_temp.expect_error(format('select public.get_safety_removal_status_v1(%L,%L)',current_setting('test.case'),repeat('b',64)),'Receipt not found');
select pg_temp.check_true(not (public.get_safety_removal_status_v1(current_setting('test.case')::uuid,current_setting('test.secret')) ?| array['request','token_hash','assigned_to','report_id']),'public status excludes sensitive fields');
reset role;
select pg_temp.check_true((select count(*)=1 from public.safety_removal_cases),'replay creates one case');
select pg_temp.check_true((select count(*)=1 from public.safety_removal_alerts),'one durable alert intent');
select pg_temp.check_true((select deadline_at=received_at+interval '48 hours' from public.safety_removal_cases),'deadline anchored exactly to receipt');
select pg_temp.check_true(not has_function_privilege('anon','public.submit_safety_removal_v1(uuid,text,jsonb)','EXECUTE'),'anonymous cannot bypass Edge');
select pg_temp.check_true(not has_function_privilege('authenticated','public.get_admin_safety_removal_v1(uuid)','EXECUTE'),'member cannot read case');
select pg_temp.check_true(not has_function_privilege('doji_employee','public.safety_removal_public_result_v1(uuid)','EXECUTE'),'internal projection helper private');
select set_config('request.jwt.claims',jsonb_build_object('role','doji_employee','aal','aal1','sub',current_setting('test.employee'))::text,true);
set local role doji_employee;
select pg_temp.expect_error(format('select public.get_admin_safety_removal_v1(%L)',current_setting('test.case')),'Restricted employee');
select set_config('request.jwt.claims',jsonb_build_object('role','doji_employee','aal','aal2','sub',current_setting('test.employee'))::text,true);
select pg_temp.check_true(public.get_admin_safety_removal_v1(current_setting('test.case')::uuid)#>>'{request,name}'='Synthetic requester','restricted exact case details');
select pg_temp.check_true(jsonb_array_length(public.get_admin_safety_removals_v1()->'items')=1,'bounded staff queue');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,1,'11111111-1111-4111-8111-111111111111','{"action":"claim","note":"Assign for restricted review"}');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,1,'11111111-1111-4111-8111-111111111111','{"action":"claim","note":"Assign for restricted review"}');
select pg_temp.expect_error(format('select public.admin_safety_removal_command_v1(%L,1,%L,%L)',current_setting('test.case'),'22222222-1111-4111-8111-111111111111','{"action":"reviewing","note":"Concurrent stale reviewer"}'),'Case changed');
select pg_temp.expect_error(format('select public.admin_safety_removal_command_v1(%L,2,%L,%L)',current_setting('test.case'),'22222222-1111-4111-8111-111111111111','{"action":"removed","note":"Cannot claim arbitrary removal","message":"All content removed"}'),'linked moderation');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,2,'33333333-1111-4111-8111-111111111111','{"action":"needs_information","note":"Need a content location","message":"Please provide the username or content reference."}');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,3,'44444444-1111-4111-8111-111111111111','{"action":"not_actionable","note":"Synthetic request not hosted here","message":"We could not locate this content on Doji; contact support with more information."}');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,4,'55555555-1111-4111-8111-111111111111','{"action":"reopen","note":"Requester provided more information","message":"Your additional information is being reviewed."}');
reset role;
select pg_temp.check_true((select revision=5 and deadline_at=received_at+interval '48 hours' and closed_at is null from public.safety_removal_cases),'reopen retains original deadline and exact revisions');
select pg_temp.check_true(not exists(select 1 from public.admin_audit_log where entity_type='safety_removal' and (reason is not null or metadata::text like '%test.invalid%')),'global audit excludes private request notes');
select pg_temp.check_true((select count(*)=1 from public.domain_event_outbox where event_type='moderation.safety.received'),'one staff invalidation on retry');
-- Revoked role cannot read a stale session's case.
select set_config('request.jwt.claims','{"role":"service_role"}',true);
set local role service_role;
select set_config('test.alerts',public.claim_safety_removal_alerts_v1('{"from":"Doji <test@test.invalid>","to":"faheygs@gmail.com"}')::text,true);
select pg_temp.check_true(jsonb_array_length(current_setting('test.alerts')::jsonb)=1,'one alert leased');
select pg_temp.check_true(jsonb_array_length(public.claim_safety_removal_alerts_v1('{"from":"Doji <test@test.invalid>","to":"faheygs@gmail.com"}'))=0,'active lease prevents duplicate sends');
select pg_temp.check_true(not public.finish_safety_removal_alert_v1(current_setting('test.case')::uuid,gen_random_uuid(),null,false),'stale worker cannot acknowledge');
select pg_temp.check_true(public.finish_safety_removal_alert_v1(current_setting('test.case')::uuid,(current_setting('test.alerts')::jsonb#>>'{0,lease_id}')::uuid,null,false),'uncertain delivery remains recoverable');
reset role;
update public.safety_removal_alerts set next_attempt_at=clock_timestamp()-interval '1 second';
set local role service_role;
select set_config('test.alerts',public.claim_safety_removal_alerts_v1('{"from":"Different <changed@test.invalid>","to":"faheygs@gmail.com"}')::text,true);
select pg_temp.check_true(current_setting('test.alerts')::jsonb#>>'{0,envelope,from}'='Doji <test@test.invalid>','retry freezes original envelope');
select pg_temp.check_true(public.finish_safety_removal_alert_v1(current_setting('test.case')::uuid,(current_setting('test.alerts')::jsonb#>>'{0,lease_id}')::uuid,'<synthetic@dojipro.com>',false,'queued'),'Cloudflare message ID and queued acceptance recorded');
reset role;
select pg_temp.check_true((select state='accepted' and provider_delivery_status='queued' and attempts=2 from public.safety_removal_alerts),'accepted is not inbox-delivered');
update public.safety_removal_alerts set state='pending',first_attempt_at=clock_timestamp()-interval '24 hours',next_attempt_at=clock_timestamp();
set local role service_role;
select pg_temp.check_true(public.claim_safety_removal_alerts_v1('{"from":"Doji <test@test.invalid>","to":"faheygs@gmail.com"}')='[]','no retries after operational retry ceiling');
reset role;
select pg_temp.check_true((select state='needs_attention' from public.safety_removal_alerts),'expired uncertain email requires operator attention');
select set_config('request.jwt.claims',jsonb_build_object('role','doji_employee','aal','aal2','sub',current_setting('test.employee'))::text,true);
update public.admin_employees set roles=array['moderator'] where id=current_setting('test.employee')::uuid;
set local role doji_employee;
select pg_temp.expect_error(format('select public.get_admin_safety_removal_v1(%L)',current_setting('test.case')),'Case unavailable');
reset role;
