select pg_temp.denied($q$select portal_identity_private.business_privacy_target(current_setting('test.access.id')::uuid,'https://business.test','business-test')$q$,'privacy gate is disabled by installation','55000');
update portal_identity_private.business_privacy_settings set enabled=true;
select pg_temp.ok(portal_identity_private.export_business_identity_target(current_setting('test.access.id')::uuid,1,'https://business.test','business-test')->>'subject'='user_independent','export maps exact reviewed account to business subject');
select pg_temp.denied($q$select portal_identity_private.export_business_identity_target(current_setting('test.access.id')::uuid,2,'https://business.test','business-test')$q$,'export rejects stale revision','PT409');
select pg_temp.denied($q$select portal_identity_private.export_business_identity_target(current_setting('test.access.id')::uuid,1,'https://employee.test','employee-test')$q$,'export rejects wrong provider directory');
select pg_temp.denied($q$select portal_identity_private.export_business_identity_target(current_setting('test.correction.id')::uuid,2,'https://business.test','business-test')$q$,'export requires access case','PT409');
update business_session_private.settings set enabled=true,scope_hash=repeat('a',64);
update business_private.accounts set disabled=false where id=current_setting('test.business.id')::uuid;
grant doji_business_session to postgres;
set local role doji_business_session;
select pg_temp.ok(business_session_private.put_bound_session(repeat('a',64),repeat('b',64),repeat('c',64),10000,'https://business.test','business-test','user_independent','session_test')->>'state'='ok','bound business session created atomically');
reset role;
select pg_temp.ok((select business_principal=current_setting('test.business.id')::uuid from business_session_private.records where key_hash=repeat('b',64)),'session belongs to exact business principal');
update business_private.accounts set disabled=true where id=current_setting('test.business.id')::uuid;
set local role doji_business_session;
select pg_temp.denied($q$select business_session_private.put_bound_session(repeat('a',64),repeat('d',64),repeat('c',64),10000,'https://business.test','business-test','user_independent','session_test')$q$,'late callback cannot create session after closure');
reset role;
update business_private.privacy_cases set state='prepared',execution_id=null where id=current_setting('test.erasure.id')::uuid;
update business_private.privacy_controls set hold_reference='case:legal-hold' where account_id=current_setting('test.business.id')::uuid;
select pg_temp.denied($q$select portal_identity_private.claim_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test')$q$,'legal hold blocks provider deletion claim','55000');
update business_private.privacy_controls set hold_reference=null where account_id=current_setting('test.business.id')::uuid;
select pg_temp.ok(portal_identity_private.claim_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test')->>'delete_authorized'='true','one durable claim authorizes provider delete');
select pg_temp.ok(portal_identity_private.claim_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test')->>'delete_authorized'='false','replayed execution never authorizes another provider delete');
select pg_temp.denied($q$select portal_identity_private.claim_business_identity_erasure(current_setting('test.erasure.id')::uuid,gen_random_uuid(),'https://business.test','business-test')$q$,'another execution cannot take over uncertain deletion','PT409');
select pg_temp.denied($q$select portal_identity_private.finish_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test','user_independent','supabase-user-absent')$q$,'Supabase absence is not WorkOS deletion proof');
select pg_temp.denied($q$select portal_identity_private.finish_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test','user_wrong','workos-404:'||repeat('a',64))$q$,'provider proof binds exact subject');
select pg_temp.ok(portal_identity_private.finish_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test','user_independent','workos-404:'||repeat('a',64))->>'state'='primary_erased','exact proven deletion erases business primary data');
select pg_temp.ok(portal_identity_private.finish_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test','user_independent','workos-404:'||repeat('a',64))->>'state'='primary_erased','finish replay is idempotent');
select pg_temp.ok((select state='deleted' from portal_identity_private.principals where id=current_setting('test.business.id')::uuid),'only business principal tombstoned');
select pg_temp.ok((select revoked from portal_identity_private.identities where principal_id=current_setting('test.business.id')::uuid),'business identity revoked');
select pg_temp.ok(not exists(select 1 from business_session_private.records where business_principal=current_setting('test.business.id')::uuid),'target business sessions removed');
select pg_temp.ok((select details='{}'::jsonb from business_private.applications where id=current_setting('test.application.id')::uuid),'application personal details erased');
select pg_temp.ok(not exists(select 1 from business_private.submissions where application_id=current_setting('test.application.id')::uuid and details<>'{}'::jsonb),'submitted personal details erased');
select pg_temp.ok(not exists(select 1 from business_private.history where application_id=current_setting('test.application.id')::uuid and (response<>'' or internal_note<>'')),'history personal free text erased');
select pg_temp.ok(not exists(select 1 from business_private.receipts where application_id=current_setting('test.application.id')::uuid and outcome<>'{"privacy_erased":true}'::jsonb),'retry snapshots do not retain erased content');
select pg_temp.ok(exists(select 1 from business_private.signup_agreements where account_id=current_setting('test.business.id')::uuid),'agreement evidence retained');
select pg_temp.denied($q$select portal_identity_private.read_business_application('https://business.test','business-test','user_independent','session_test',false)$q$,'deleted identity cannot use old session');
select pg_temp.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace,
 unnest(array['anon','authenticated','service_role','doji_employee','doji_business','doji_identity_resolver','doji_business_enrollment','doji_business_session']) r
 where n.nspname='portal_identity_private' and p.proname in('business_privacy_target','export_business_identity_target','claim_business_identity_erasure','finish_business_identity_erasure') and has_function_privilege(r,p.oid,'execute')),'privacy operator functions inaccessible to all API roles');
update portal_identity_private.business_privacy_settings set enabled=false;
select pg_temp.denied($q$select portal_identity_private.claim_business_identity_erasure(current_setting('test.erasure.id')::uuid,'88000000-0000-4000-8000-000000000002','https://business.test','business-test')$q$,'rollback switch disables even completed-case operator reads','55000');
