-- Offline synthetic transaction only; existing test identities from auth suite.
select pg_temp.check_true(not (select enabled or registration_open from business_private.public_auth_settings),'public admission installs closed');
select pg_temp.check_true((select count(*)=4096 from business_private.public_auth_buckets),'public limiter storage is fixed');
select pg_temp.check_true(not has_table_privilege('service_role','business_private.public_auth_settings','select,insert,update,delete'),'public settings inaccessible to service table API');
select pg_temp.check_true(not has_function_privilege('anon','public.claim_public_business_auth_v1(text,text)','execute'),'anonymous cannot bypass public proof');
select pg_temp.check_true(not has_function_privilege('authenticated','public.claim_public_business_auth_v1(text,text)','execute'),'member cannot call public admission');
select pg_temp.check_true(not has_function_privilege('doji_business','public.claim_public_business_auth_v1(text,text)','execute'),'business cannot call public admission');
select pg_temp.check_true(not has_function_privilege('doji_employee','public.claim_public_business_auth_v1(text,text)','execute'),'employee cannot call public admission');
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('register','public-new@test.invalid')->>'allowed'='false','public registration default off');
reset role;
update business_private.public_auth_settings set enabled=true,registration_open=true,admission_until=now()+interval '1 hour',registration_limit=2,email_limit=4,daily_email_limit=3;
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('register','public-new@test.invalid')->>'allowed'='true','uninvited public email reserves account and email');
select pg_temp.check_true(public.claim_public_business_auth_v1('register','public-new@test.invalid')->>'allowed'='false','duplicate creation throttled before downstream Auth');
select pg_temp.check_true(public.claim_public_business_auth_v1('register',current_setting('test.member.email'))->>'allowed'='false','public registration cannot convert member');
select pg_temp.check_true(public.claim_public_business_auth_v1('signin',current_setting('test.member.email'))->>'allowed'='false','public login cannot exchange member password');
select pg_temp.check_true(public.claim_public_business_auth_v1('recover',current_setting('test.employee.email'))->>'allowed'='false','public recovery cannot send employee email');
select pg_temp.check_true(public.claim_public_business_auth_v1('verify',current_setting('test.member.email'))->>'allowed'='false','public verification rejects member identity');
select pg_temp.check_true(public.claim_public_business_auth_v1('signin','pilot-unconfirmed@test.invalid')->>'allowed'='false','public login requires verified email');
select pg_temp.check_true(public.claim_public_business_auth_v1('register','public-next@test.invalid')->>'allowed'='true','second public account admitted');
select pg_temp.check_true(public.claim_public_business_auth_v1('register','public-third@test.invalid')->>'allowed'='false','public account cap cannot be exceeded');
select pg_temp.check_true(public.claim_public_business_auth_v1('resend','pilot-unconfirmed@test.invalid')->>'allowed'='true','public resend uses third daily reservation');
select pg_temp.check_true(public.claim_public_business_auth_v1('recover','pilot-confirmed@test.invalid')->>'allowed'='false','public daily mail budget rejects excess');
select pg_temp.check_true(public.claim_public_business_auth_v1('verify','pilot-unconfirmed@test.invalid')->>'allowed'='true','mail cap does not block redemption');
reset role;
update business_private.public_auth_settings set registration_open=false,admission_until=now()-interval '1 hour';
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('signin','pilot-confirmed@test.invalid')->>'user_id'='73000000-0000-4000-8000-000000000001','closing signup does not lock existing businesses out');
reset role;
update business_private.public_auth_settings set day_at=(now() at time zone 'UTC')::date-1;
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('recover','pilot-confirmed@test.invalid')->>'allowed'='true','UTC day rollover permits remaining lifetime mail reservation');
reset role;
update business_private.public_auth_buckets set last_mail_at=null;
update business_private.public_auth_settings set day_at=(now() at time zone 'UTC')::date-1;
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('resend','pilot-unconfirmed@test.invalid')->>'allowed'='false','daily rollover never refills lifetime email cap');
reset role;
select pg_temp.check_true((select emails_used=4 and registrations_used=2 from business_private.public_auth_settings),'exact conservative public lifetime reservations');
update business_private.public_auth_settings set registration_limit=3,registration_open=true;
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('register','public-third@test.invalid')->>'allowed'='false','expired admission never creates new identity');
reset role;
update business_private.accounts set disabled=true where id='73000000-0000-4000-8000-000000000001';
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('signin','pilot-confirmed@test.invalid')->>'allowed'='false','public login denies disabled business');
select pg_temp.check_true(public.claim_public_business_auth_v1('verify','pilot-confirmed@test.invalid')->>'allowed'='false','public verification denies disabled business');
reset role;
update business_private.accounts set disabled=false where id='73000000-0000-4000-8000-000000000001';
update business_private.public_auth_buckets set attempts=30;
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('signin','pilot-confirmed@test.invalid')->>'allowed'='false','fixed-slot per-address limiter enforced');
reset role;
update business_private.public_auth_buckets set window_at=now()-interval '2 hours';
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('signin','pilot-confirmed@test.invalid')->>'allowed'='true','hourly address limiter can recover without polling');
reset role;
update business_private.public_auth_settings set attempts=600;
set local role service_role;
select pg_temp.check_true(public.claim_public_business_auth_v1('signin','pilot-confirmed@test.invalid')->>'allowed'='false','global public attempt limiter enforced');
reset role;
select pg_temp.check_true((select count(*)=4096 from business_private.public_auth_buckets),'untrusted addresses never grow limiter table');
select pg_temp.check_true(not exists(select 1 from business_private.auth_budgets where email like 'public-%'),'public admission does not use invitation budgets');
