-- Same rollback-only synthetic transaction, after intake/alert checks.
update public.admin_employees set roles=array['super_admin'] where id=current_setting('test.employee')::uuid;
select set_config('request.jwt.claims','{}',true);
do $$declare author uuid:=gen_random_uuid(); viewer uuid:=gen_random_uuid(); challenge uuid:=gen_random_uuid();
 event uuid:=gen_random_uuid(); participation uuid:=gen_random_uuid(); post uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email,role,aud) values(author,author::text||'@test.invalid','authenticated','authenticated'),(viewer,viewer::text||'@test.invalid','authenticated','authenticated');
 update auth.users set raw_user_meta_data=jsonb_build_object('terms_version','2026-08-20','privacy_version','2026-08-20','terms_accepted_at',now(),'privacy_accepted_at',now()) where id in(author,viewer);
 insert into public.profiles(id,username,display_name) values(author,'a'||left(replace(author::text,'-',''),16),'Synthetic author'),(viewer,'v'||left(replace(viewer::text,'-',''),16),'Synthetic viewer');
 insert into public.challenges(id,title,description,category) values(challenge,'Safety bridge fixture','Synthetic only','creative');
 insert into public.daily_events(id,challenge_id,fires_at) values(event,challenge,now()-interval '2 minutes');
 insert into public.user_events(id,user_id,daily_event_id,status,expires_at) values(participation,author,event,'completed',now()+interval '8 minutes'),(gen_random_uuid(),viewer,event,'completed',now()+interval '8 minutes');
 insert into storage.buckets(id,name) values('post-media','post-media') on conflict do nothing;
 insert into storage.objects(bucket_id,name,owner_id) values('post-media',post::text||'.jpg',author::text);
 insert into public.media_upload_intents(user_id,user_event_id,idempotency_key,slot,object_path,content_type) values(author,participation,post::text,'photo',post::text||'.jpg','image/jpeg');
 insert into public.posts(id,user_id,user_event_id,daily_event_id,idempotency_key,photo_url) values(post,author,participation,event,post::text,'https://test.invalid/storage/v1/object/public/post-media/'||post::text||'.jpg');
 perform set_config('test.post',post::text,true);perform set_config('test.author',author::text,true);perform set_config('test.viewer',viewer::text,true);
end$$;
select pg_temp.check_true(not has_table_privilege('doji_employee','public.reports','INSERT'),'no direct employee report insertion');
select pg_temp.check_true(not has_function_privilege('authenticated','public.admin_create_safety_report_v1(uuid,bigint,uuid,jsonb)','EXECUTE'),'members cannot use staff bridge');
select set_config('request.jwt.claims',jsonb_build_object('role','doji_employee','aal','aal2','sub',current_setting('test.employee'))::text,true);
set local role doji_employee;
select set_config('test.target',public.get_admin_safety_target_v1(current_setting('test.case')::uuid,'post',current_setting('test.post')::uuid)::text,true);
select set_config('test.handoff',jsonb_build_object('kind','post','target_id',current_setting('test.post'),'fingerprint',current_setting('test.target')::jsonb->>'fingerprint','note','Verified exact synthetic content location')::text,true);
select pg_temp.expect_error(format('select public.admin_create_safety_report_v1(%L,5,%L,%L)',current_setting('test.case'),'99999999-1111-4111-8111-111111111111',(current_setting('test.handoff')::jsonb||jsonb_build_object('fingerprint',repeat('f',64)))::text),'Content changed');
select set_config('test.handoff_result',public.admin_create_safety_report_v1(current_setting('test.case')::uuid,5,'99999999-1111-4111-8111-111111111111',current_setting('test.handoff')::jsonb)::text,true);
select pg_temp.check_true(public.admin_create_safety_report_v1(current_setting('test.case')::uuid,5,'99999999-1111-4111-8111-111111111111',current_setting('test.handoff')::jsonb)=current_setting('test.handoff_result')::jsonb,'handoff replay same result');
reset role;
select pg_temp.check_true((select count(*)=1 from public.reports where id=(current_setting('test.handoff_result')::jsonb->>'report_id')::uuid and reporter_id is null and notes not like '%test.invalid%'),'one report without external identity');
select pg_temp.check_true((select moderation_status='quarantined' from public.posts where id=current_setting('test.post')::uuid),'explicit staff confirmation quarantines exact content');
select pg_temp.check_true((select queue='restricted_safety' from public.admin_report_triage where report_id=(current_setting('test.handoff_result')::jsonb->>'report_id')::uuid),'handoff routes restricted');
select pg_temp.check_true(not exists(select 1 from public.domain_event_outbox where topic is null),'no null reporter event');
-- Normal member reports retain their original rate budget, receipt and private event.
select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',current_setting('test.viewer'))::text,true);
set local role authenticated;
select set_config('test.member_report',public.submit_policy_report(current_setting('test.author')::uuid,null,null,null,'account','other','other',null,'safety-member-regression')::text,true);
select pg_temp.check_true(public.submit_policy_report(current_setting('test.author')::uuid,null,null,null,'account','other','other',null,'safety-member-regression')=current_setting('test.member_report')::jsonb,'member report receipt unchanged');
reset role;
select pg_temp.check_true(exists(select 1 from public.api_rate_limit_buckets where user_id=current_setting('test.viewer')::uuid and action='report'),'member limiter still used');
select pg_temp.check_true(exists(select 1 from public.domain_event_outbox where topic='user:'||current_setting('test.viewer')||':events' and aggregate_id=(current_setting('test.member_report')::jsonb->>'id')::uuid),'member private invalidation preserved');
-- The existing moderation command, not intake status, authorizes removal.
select set_config('request.jwt.claims',jsonb_build_object('role','doji_employee','aal','aal2','sub',current_setting('test.employee'))::text,true);
set local role doji_employee;
select public.admin_decide_report_v3((current_setting('test.handoff_result')::jsonb->>'report_id')::uuid,'remove_content','sexual_content','level_2','Synthetic restricted content finding','Synthetic content removal notice','warning',null,'safety-bridge-decision');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,6,'77777777-1111-4111-8111-111111111111','{"action":"removed","note":"Synthetic verification completed","message":"The identified content has been removed.","copies_review":"Synthetic identical-copy investigation documented.","access_review":"Synthetic access checks recorded; hosted CDN is not tested here."}');
reset role;
select pg_temp.check_true((select state='removed' from public.safety_removal_cases where id=current_setting('test.case')::uuid),'existing moderation decision closes intake');
select set_config('test.decision',(select id::text from public.moderation_decisions where report_id=(current_setting('test.handoff_result')::jsonb->>'report_id')::uuid limit 1),true);
select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',current_setting('test.author'))::text,true);
set local role authenticated;
select public.submit_moderation_appeal(current_setting('test.decision')::uuid,'Synthetic request for another review','safety-bridge-appeal');
reset role;
select set_config('test.appeal',(select id::text from public.moderation_appeals where decision_id=current_setting('test.decision')::uuid),true);
select set_config('request.jwt.claims',jsonb_build_object('role','doji_employee','aal','aal2','sub',current_setting('test.employee'))::text,true);
set local role doji_employee;
select public.admin_review_moderation_appeal(current_setting('test.appeal')::uuid,'reverse','Synthetic final-authority appeal reversal','safety-bridge-reversal');
select public.admin_safety_removal_command_v1(current_setting('test.case')::uuid,7,'88888888-1111-4111-8111-111111111111','{"action":"reopen","note":"Review the reversed moderation decision","message":"This request is under renewed review."}');
select pg_temp.expect_error(format('select public.admin_safety_removal_command_v1(%L,8,%L,%L)',current_setting('test.case'),'66666666-1111-4111-8111-111111111111','{"action":"removed","note":"Cannot close using a reversed decision","message":"The identified content was removed.","copies_review":"Synthetic identical-copy checks complete.","access_review":"Synthetic access checks cannot override the actual content state."}'),'linked moderation decision');
reset role;
