create function pg_temp.check_true(ok boolean,label text) returns text language plpgsql as $$begin
 if ok is distinct from true then raise exception 'FAIL: %',label; end if;
 return 'PASS: '||label;
end$$;
create function pg_temp.expect_error(command text,fragment text) returns text language plpgsql as $$begin
 begin execute command; exception when others then
  if position(fragment in sqlerrm)>0 then return 'PASS: denied '||fragment; end if; raise; end;
 raise exception 'FAIL: expected error containing %',fragment;
end$$;
select set_config('test.employee',id::text,true) from public.admin_employees where 'super_admin'=any(roles) limit 1;
select set_config('test.member',id::text,true) from auth.users where role='authenticated' limit 1;
select set_config('test.business','71000000-0000-4000-8000-000000000001',true);
select set_config('test.other','71000000-0000-4000-8000-000000000002',true);
insert into auth.users(id,email,role,raw_app_meta_data,raw_user_meta_data,email_confirmed_at) values
 (current_setting('test.business')::uuid,'business-one@test.invalid','doji_business','{"account_type":"business"}','{}',now()),
 (current_setting('test.other')::uuid,'business-two@test.invalid','doji_business','{"account_type":"business"}','{}',now());
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal1')::text,true);
set local role doji_business;
select pg_temp.expect_error('select public.get_business_application_v1()','not enabled');
reset role;
update business_private.settings set enabled=true,application_terms_version='test-terms-v1',privacy_version='test-privacy-v1';
select pg_temp.check_true(not (select realtime_enabled from business_private.settings),'realtime producers default off');
update business_private.settings set realtime_enabled=true;
select pg_temp.check_true(not pg_has_role('authenticator','doji_business','member'),'no API activation in draft');
select pg_temp.check_true(not pg_has_role('doji_business','authenticated','member'),'business cannot inherit member role');
select pg_temp.check_true(not pg_has_role('doji_business','doji_employee','member'),'business cannot inherit employee role');
select pg_temp.check_true(not has_table_privilege('doji_business','public.profiles','select,insert,update,delete'),'no member profile access');
select pg_temp.check_true(not has_table_privilege('doji_business','storage.objects','select,insert,update,delete'),'no media access');
select pg_temp.check_true(not has_function_privilege('doji_business','public.get_own_profile()','execute'),'member RPC denied');
select pg_temp.check_true(not has_function_privilege('authenticated','public.get_business_application_v1()','execute'),'member cannot read business application');
select pg_temp.check_true(not has_function_privilege('service_role','public.admin_business_application_command_v1(uuid,bigint,text,text,text,uuid)','execute'),'service defaults cannot approve');
select pg_temp.check_true(not has_function_privilege('doji_business','public.get_admin_business_application_v1(uuid)','execute'),'business cannot read staff detail');
select pg_temp.check_true(not has_schema_privilege('doji_business','business_private','usage'),'private schema unavailable');
set local role doji_business;
select pg_temp.check_true(public.get_business_application_v1() is null,'new account has no fabricated application');
select pg_temp.expect_error('select public.get_business_workspace_v1()','requires MFA');
select pg_temp.expect_error($q$select public.business_application_command_v1('save',null,'{"state":"approved"}',null,null,gen_random_uuid())$q$,'Unsupported application field');
select pg_temp.expect_error($q$select public.business_application_command_v1('submit',null,'{}','test-terms-v1','test-privacy-v1',gen_random_uuid())$q$,'Complete all application fields');
select pg_temp.expect_error($q$select public.business_application_command_v1('save',null,'{"website":"javascript:alert(1)"}',null,null,gen_random_uuid())$q$,'public HTTPS');
select set_config('test.details','{"legal_name":"Example LLC","brand_name":"Example","website":"https://example.test","country":"US","business_address":"123 Example St","representative_name":"Test Owner","representative_role":"Owner","category":"Retail","purpose":"Evaluate a future pilot"}',true);
select set_config('test.saved',public.business_application_command_v1('save',null,current_setting('test.details')::jsonb,null,null,'72000000-0000-4000-8000-000000000001')::text,true);
select set_config('test.application',current_setting('test.saved')::jsonb#>>'{outcome,id}',true);
select pg_temp.check_true(current_setting('test.saved')::jsonb#>>'{outcome,state}'='draft','save creates a draft');
select pg_temp.check_true(public.business_application_command_v1('save',null,current_setting('test.details')::jsonb,null,null,'72000000-0000-4000-8000-000000000001')->>'replayed'='true','exact replay uses receipt');
select pg_temp.expect_error($q$select public.business_application_command_v1('save',null,'{}',null,null,'72000000-0000-4000-8000-000000000001')$q$,'different command');
select pg_temp.expect_error($q$select public.business_application_command_v1('save',0,'{}',null,null,gen_random_uuid())$q$,'Application changed');
select pg_temp.expect_error($q$select public.business_application_command_v1('submit',1,current_setting('test.details')::jsonb,'old','test-privacy-v1',gen_random_uuid())$q$,'current application terms');
select pg_temp.check_true(public.business_application_command_v1('submit',1,current_setting('test.details')::jsonb,'test-terms-v1','test-privacy-v1','72000000-0000-4000-8000-000000000002')#>>'{outcome,state}'='pending','submission enters review');
select pg_temp.expect_error($q$select public.business_application_command_v1('save',2,'{}',null,null,gen_random_uuid())$q$,'cannot be edited');
reset role;
select pg_temp.check_true((select count(*)=1 from business_private.submissions),'one immutable submission');
select pg_temp.check_true((select count(*)=0 from business_private.organizations),'pending cannot create workspace');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.other'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.check_true(public.get_business_application_v1() is null,'other business cannot see application');
select pg_temp.expect_error('select public.get_business_workspace_v1()','Approved organization');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.member'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.expect_error('select public.get_business_application_v1()','Verified business');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal1')::text,true);
set local role doji_employee;
select pg_temp.expect_error('select public.get_admin_business_applications_page_v1()','employee MFA');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(jsonb_array_length(public.get_admin_business_applications_page_v1()->'items')=1,'authorized staff queue includes submitted application');
select pg_temp.expect_error($q$select public.get_admin_business_applications_page_v1('pending',51)$q$,'Invalid page parameters');
select pg_temp.check_true(public.admin_business_application_command_v1(current_setting('test.application')::uuid,2,'request_changes','Please correct the company address.','INTERNAL ONLY verify domain ownership.','72000000-0000-4000-8000-000000000003')#>>'{outcome,state}'='changes_requested','staff requests changes');
select pg_temp.check_true(position('INTERNAL ONLY' in public.get_admin_business_application_v1(current_setting('test.application')::uuid)::text)>0,'internal note visible to authorized staff');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.check_true(position('INTERNAL ONLY' in public.get_business_application_v1()::text)=0,'internal note never exposed to applicant');
select pg_temp.check_true(public.get_business_application_v1()->>'response'='Please correct the company address.','applicant receives its review response');
select pg_temp.check_true(public.business_application_command_v1('submit',3,current_setting('test.details')::jsonb||'{"business_address":"456 Corrected St"}','test-terms-v1','test-privacy-v1','72000000-0000-4000-8000-000000000004')#>>'{outcome,revision}'='4','resubmit advances exact version');
reset role;
select pg_temp.check_true((select details->>'business_address'='123 Example St' from business_private.submissions where submission=1),'revision preserves original submission');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.expect_error($q$select public.admin_business_application_command_v1(current_setting('test.application')::uuid,2,'approve','Application approved for workspace access.','Review complete with synthetic checks.',gen_random_uuid())$q$,'Application changed');
select pg_temp.check_true(public.admin_business_application_command_v1(current_setting('test.application')::uuid,4,'approve','Application approved for workspace access.','Review complete with synthetic checks.','72000000-0000-4000-8000-000000000005')#>>'{outcome,state}'='approved','approval commits');
select pg_temp.check_true(public.admin_business_application_command_v1(current_setting('test.application')::uuid,4,'approve','Application approved for workspace access.','Review complete with synthetic checks.','72000000-0000-4000-8000-000000000005')->>'replayed'='true','approval replay does not duplicate');
reset role;
select pg_temp.check_true((select count(*)=1 from business_private.organizations),'one organization after approval replay');
select pg_temp.check_true((select count(*)=1 from business_private.memberships),'one owner membership');
select pg_temp.check_true((select count(*)=2 from public.admin_audit_log where entity_id=current_setting('test.application')),'exactly one audit row per review');
select set_config('test.organization',id::text,true) from business_private.organizations;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.check_true(public.get_business_workspace_v1()->>'organization_id'=current_setting('test.organization'),'approved owner reads only own workspace');
select pg_temp.check_true(public.get_business_workspace_v1()->>'campaigns_enabled'='false','approval cannot publish campaigns');
reset role;
update business_private.accounts set disabled=true where id=current_setting('test.business')::uuid;
set local role doji_business;
select pg_temp.expect_error('select public.get_business_workspace_v1()','Business access disabled');
select pg_temp.expect_error($q$select public.business_application_command_v1('save',null,current_setting('test.details')::jsonb,null,null,'72000000-0000-4000-8000-000000000001')$q$,'Business access disabled');
reset role;
update business_private.accounts set disabled=false where id=current_setting('test.business')::uuid;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(public.admin_business_application_command_v1(current_setting('test.application')::uuid,5,'reopen','We need to recheck representative authority.','Synthetic reopen qualification only.','72000000-0000-4000-8000-000000000006')#>>'{outcome,state}'='changes_requested','reopen requires a new review');
reset role;
select pg_temp.check_true((select status='suspended' from business_private.organizations),'reopen atomically suspends workspace');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.expect_error('select public.get_business_workspace_v1()','Approved organization');
reset role;
-- Unsaved-to-review changes must not appear as the submitted evidence to staff.
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.check_true(public.business_application_command_v1('save',6,current_setting('test.details')::jsonb||'{"brand_name":"PRIVATE DRAFT"}',null,null,gen_random_uuid())#>>'{outcome,revision}'='7','reopened applicant can save a private draft');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(public.get_admin_business_application_v1(current_setting('test.application')::uuid)#>>'{details,brand_name}'='Example','staff evidence excludes unsent draft');
select pg_temp.check_true(public.get_admin_business_applications_page_v1('changes_requested')#>>'{items,0,brand_name}'='Example','staff queue excludes unsent draft');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.check_true(public.get_business_application_v1()#>>'{details,brand_name}'='PRIVATE DRAFT','applicant can resume its own draft');
select pg_temp.check_true(public.business_application_command_v1('submit',7,current_setting('test.details')::jsonb,'test-terms-v1','test-privacy-v1',gen_random_uuid())#>>'{outcome,state}'='pending','reopened application can resubmit');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(public.admin_business_application_command_v1(current_setting('test.application')::uuid,8,'approve','Your application is approved again.','Synthetic reapproval verification.',gen_random_uuid())#>>'{outcome,state}'='approved','reapproval succeeds');
reset role;
select pg_temp.check_true((select count(*)=1 and min(id::text)=current_setting('test.organization') from business_private.organizations),'reapproval reuses organization');
select pg_temp.check_true((select count(*)=1 from business_private.memberships),'reapproval preserves one owner');
-- Bounded success budget cannot be bypassed with more request IDs; replay does not spend it.
update business_private.accounts set budget_used=60 where id=current_setting('test.business')::uuid;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.expect_error($q$select public.business_application_command_v1('save',9,'{}',null,null,gen_random_uuid())$q$,'change limit reached');
select pg_temp.check_true(public.business_application_command_v1('save',null,current_setting('test.details')::jsonb,null,null,'72000000-0000-4000-8000-000000000001')->>'replayed'='true','receipt replay still works at change limit');
reset role;
-- Another real applicant provides pagination and decline coverage.
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.other'),'role','doji_business','aal','aal1')::text,true);
set local role doji_business;
select set_config('test.other_application',public.business_application_command_v1('submit',null,current_setting('test.details')::jsonb,'test-terms-v1','test-privacy-v1',gen_random_uuid())#>>'{outcome,id}',true);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(public.admin_business_application_command_v1(current_setting('test.other_application')::uuid,1,'decline','We cannot approve this application.','Synthetic decline qualification.',gen_random_uuid())#>>'{outcome,state}'='declined','decline is recorded');
reset role;
select pg_temp.check_true(not exists(select 1 from business_private.organizations where application_id=current_setting('test.other_application')::uuid),'decline never creates workspace');
-- Synthetic equal-timestamp rows exercise the id tie-break in the read-only page.
insert into business_private.accounts(id) values('73000000-0000-4000-8000-000000000001'),('73000000-0000-4000-8000-000000000002');
insert into business_private.applications(id,applicant_id,state,submission,updated_at) values
 ('74000000-0000-4000-8000-000000000001','73000000-0000-4000-8000-000000000001','pending',1,'2026-01-01'),
 ('74000000-0000-4000-8000-000000000002','73000000-0000-4000-8000-000000000002','pending',1,'2026-01-01');
insert into business_private.submissions select id,1,current_setting('test.details')::jsonb,'test-terms-v1','test-privacy-v1',now()
 from business_private.applications where applicant_id in('73000000-0000-4000-8000-000000000001','73000000-0000-4000-8000-000000000002');
set local role doji_employee;
select set_config('test.page',public.get_admin_business_applications_page_v1('pending',1)::text,true);
select pg_temp.check_true(jsonb_array_length(current_setting('test.page')::jsonb->'items')=1,'page bound enforced');
select pg_temp.check_true(current_setting('test.page')::jsonb#>>'{next_cursor,id}'='74000000-0000-4000-8000-000000000001','cursor uses last returned record');
select pg_temp.check_true(public.get_admin_business_applications_page_v1('pending',1,'2026-01-01','74000000-0000-4000-8000-000000000001')#>>'{items,0,id}'='74000000-0000-4000-8000-000000000002','equal timestamp cursor has no duplicate or skip');
reset role;
select pg_temp.check_true(not exists(select 1 from public.domain_event_outbox where event_type in ('business.application.updated','moderation.business.updated') and (payload - 'applicationId' - 'applicantId' - 'sendPush')<>'{}'),'events contain only identifiers and no-push flag');
select pg_temp.check_true(not exists(select 1 from public.domain_event_outbox where event_type in ('business.application.updated','moderation.business.updated') and payload->>'sendPush'<>'false'),'no member phone alerts');
select pg_temp.check_true(not exists(select 1 from public.profiles where id in(current_setting('test.business')::uuid,current_setting('test.other')::uuid)),'business users create no member profiles');
-- A read-only business reviewer cannot approve; no widening of existing staff permissions.
update public.admin_employees set roles=array['business_reviewer'] where id=current_setting('test.employee')::uuid;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.employee'),'role','doji_employee','aal','aal2')::text,true);
set local role doji_employee;
select pg_temp.check_true(public.get_admin_business_application_v1(current_setting('test.application')::uuid)->>'state'='approved','business reviewer may read');
select pg_temp.expect_error($q$select public.admin_business_application_command_v1(current_setting('test.application')::uuid,6,'approve','Approval attempted without permission.','Synthetic denial test only.',gen_random_uuid())$q$,'review permission');
reset role;
-- Removing Auth identity cannot cascade away the submitted evidence.
delete from auth.users where id=current_setting('test.business')::uuid;
select pg_temp.check_true((select count(*)=3 from business_private.submissions where application_id=current_setting('test.application')::uuid),'Auth deletion preserves review evidence');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.business'),'role','doji_business','aal','aal2')::text,true);
set local role doji_business;
select pg_temp.expect_error('select public.get_business_application_v1()','Verified business');
reset role;
