import assert from 'node:assert/strict';
import { safetyEmailRuntimeProbe as probe } from './fixtures/safety-email-runtime-probe.ts';
const now = Date.now();
const env = {serviceKeys: ['sb_secret_fixture'], enabled: 'false', accountId: '0'.repeat(32), token: 'fixture', expiresAt: now + 900_000};
const req = (action = 'verify', key = 'sb_secret_fixture', method = 'POST', body?: string) => new Request(`https://project.invalid/functions/v1/safety-removal-alerts/${action}`, {method, headers: {apikey: key}, ...(body ? {body} : {})});
const calls: {url: string; options: RequestInit | undefined}[] = [];
const upstream: typeof fetch = async (input, options) => {
  const url = input instanceof Request ? input.url : String(input);
  calls.push({url, options});
  if (url.includes('/routing/addresses')) return Response.json({success: true, result: [{email: 'faheygs@gmail.com', verified: '2026-09-01T00:00:00Z'}]});
  assert.match(url, /\/email\/sending\/send$/);
  assert.equal(typeof options?.body, 'string');
  const mail: unknown = JSON.parse(String(options?.body));
  assert.ok(mail && typeof mail==='object' && 'subject' in mail && 'to' in mail && 'text' in mail);
  assert.ok(typeof mail.text==='string');
  assert.equal(mail.subject, 'Doji · Dedicated safety email connection TEST');
  assert.equal(mail.to, 'faheygs@gmail.com');
  assert.match(mail.text, /No removal request was submitted/);
  return Response.json({success: true, result: {message_id: '<fixture@dojipro.com>', delivered: ['faheygs@gmail.com'], queued: [], permanent_bounces: []}});
};
for (const key of ['', 'wrong', 'sb_publishable_fixture']) assert.equal((await probe(req('verify', key), env, upstream, now)).status, 401);
assert.equal((await probe(req(), {...env, serviceKeys: []}, upstream, now)).status, 401);
assert.equal((await probe(req(), {...env, expiresAt: now}, upstream, now)).status, 410);
assert.equal((await probe(req(), {...env, expiresAt: now + 1_800_000}, upstream, now)).status, 410);
assert.equal((await probe(req(), {...env, enabled: 'true'}, upstream, now)).status, 409);
assert.equal((await probe(req('verify', 'sb_secret_fixture', 'GET'), env, upstream, now)).status, 405);
assert.equal((await probe(req('other'), env, upstream, now)).status, 404);
assert.equal((await probe(req('canary', 'sb_secret_fixture', 'POST', '{}'), env, upstream, now)).status, 400);
assert.equal(calls.length, 0);
let response = await probe(req(), env, upstream, now);
assert.equal(response.status, 200); assert.equal(calls.length, 1);
assert.equal(response.headers.get('cache-control'), 'no-store');
response = await probe(req('canary'), env, upstream, now);
assert.equal(response.status, 200); assert.equal(calls.length, 3);
assert.equal((await response.json()).status, 'delivered');
let sendCalls = 0;
response = await probe(req('canary'), env, async () => { sendCalls++; return Response.json({success: true, result: []}); }, now);
assert.equal(response.status, 503); assert.equal(sendCalls, 1);
response = await probe(req(), env, async () => {throw new Error('private provider text');}, now);
assert.equal(response.status, 503); assert.ok(!(await response.text()).includes('private provider'));
console.log('Temporary runtime probe: auth, expiry, disabled-only, no input, preflight, fixed canary and safe failures passed; mocked network only.');
