import { Dimensions, StyleSheet } from 'react-native';
import { Radius, Spacing } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const cameraScreenStyles = StyleSheet.create({
  container: { flex: 1 },
  chooseRoot: { flex: 1 },
  chooseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
  },
  headerButtonDark: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chooseBody: {
    flex: 1,
    paddingHorizontal: Spacing.xl,
    justifyContent: 'center',
    gap: Spacing.md,
    alignItems: 'center',
  },
  chooseTitle: { textAlign: 'center' },
  chooseSub: { textAlign: 'center', lineHeight: 22 },
  chooseButtons: { width: '100%', marginTop: Spacing.lg, gap: Spacing.sm },
  camera: { flex: 1 },
  cameraOverlay: { position: 'absolute', inset: 0, justifyContent: 'space-between' },
  captureHint: { paddingHorizontal: Spacing.xl },
  cameraFooter: { paddingBottom: Spacing.xxl, alignItems: 'center' },
  captureButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureButtonCapturing: { opacity: 0.6, transform: [{ scale: 0.95 }] },
  captureButtonInner: { width: 60, height: 60, borderRadius: 30 },
  recordOuter: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordInner: { width: 52, height: 52, borderRadius: 26 },
  recordInnerSquare: { width: 32, height: 32, borderRadius: 6 },
  permissionContainer: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.lg,
  },
  previewContent: { flexGrow: 1 },
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  previewHeaderBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  dualPhotoContainer: {
    position: 'relative',
    width: SCREEN_WIDTH,
    height: SCREEN_WIDTH,
  },
  mainPreview: { width: SCREEN_WIDTH, height: SCREEN_WIDTH },
  frontPreviewContainer: {
    position: 'absolute',
    bottom: Spacing.md,
    right: Spacing.md,
    borderRadius: Radius.md,
    overflow: 'hidden',
    borderWidth: 3,
  },
  frontPreview: { width: 90, height: 90 },
  videoPreviewWrap: { width: SCREEN_WIDTH, marginTop: Spacing.sm },
  videoPreview: { width: SCREEN_WIDTH, height: SCREEN_WIDTH * 0.5625 },
  previewFooter: { padding: Spacing.lg, gap: Spacing.md },
  captionInput: { flex: 1 },
});
