-- Blocking is a personal privacy action, not a moderation report. Keep the block
-- and friendship removal atomic, while requiring an explicit report action to
-- create work in the moderation queue.
create or replace function public.block_user(
  p_blocked_user_id uuid,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  block_id uuid;
  prior_result jsonb;
  final_result jsonb;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if p_blocked_user_id = uid then raise exception 'Cannot block yourself'; end if;
  if length(p_idempotency_key) < 16 then raise exception 'Invalid idempotency key'; end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      least(uid::text, p_blocked_user_id::text) || ':' ||
      greatest(uid::text, p_blocked_user_id::text),
      0
    )
  );

  select receipt.result into prior_result
  from public.command_receipts receipt
  where receipt.user_id = uid
    and receipt.idempotency_key = p_idempotency_key;
  if found then return prior_result; end if;

  insert into public.blocks (blocker_id, blocked_id)
  values (uid, p_blocked_user_id)
  on conflict (blocker_id, blocked_id)
  do update set blocked_id = excluded.blocked_id
  returning id into block_id;

  delete from public.friendships
  where (requester_id = uid and addressee_id = p_blocked_user_id)
     or (requester_id = p_blocked_user_id and addressee_id = uid);

  final_result := jsonb_build_object(
    'id', block_id,
    'blocked_user_id', p_blocked_user_id
  );

  insert into public.command_receipts (user_id, idempotency_key, result)
  values (uid, p_idempotency_key, final_result);

  return final_result;
end;
$$;

revoke all on function public.block_user(uuid, text) from public, anon;
grant execute on function public.block_user(uuid, text) to authenticated;

-- Remove only legacy reports that were mechanically generated by block_user.
-- Explicit user reports, including reports made alongside a block, are retained.
delete from public.reports
where status = 'pending'
  and reason = 'other'
  and notes = 'Created automatically when this account was blocked.'
  and post_id is null
  and comment_id is null
  and poll_vote_id is null;
